INTERFACE
#ifdef GPU
ATTRIBUTES (DEVICE) &
#endif
SUBROUTINE ACTKE (KLON, KLEV, KIDIA, KFDIA, KSIZE, PSTACK)

IMPLICIT NONE

INTEGER(KIND=4),INTENT(IN)    :: KLON
INTEGER(KIND=4),INTENT(IN)    :: KLEV
INTEGER(KIND=4),INTENT(IN)    :: KIDIA
INTEGER(KIND=4),INTENT(IN)    :: KFDIA
INTEGER(KIND=4),INTENT(IN)    :: KSIZE
REAL(KIND=8)   ,INTENT(INOUT) :: PSTACK(KSIZE)  
 
END SUBROUTINE ACTKE
END INTERFACE
