#include "simple4.h"
SUBROUTINE ACTKE (KLON, KLEV, KIDIA, KFDIA, KSIZE, PSTACK)

IMPLICIT NONE

INTEGER(KIND=4),INTENT(IN)    :: KLON
INTEGER(KIND=4),INTENT(IN)    :: KLEV
INTEGER(KIND=4),INTENT(IN)    :: KIDIA
INTEGER(KIND=4),INTENT(IN)    :: KFDIA
INTEGER(KIND=4),INTENT(IN)    :: KSIZE
REAL(KIND=8)   ,INTENT(INOUT) :: PSTACK(KSIZE)  

REAL(KIND=8) :: ZTMP (KLON, 0:KLEV)
POINTER (IPZTMP, ZTMP)

INTEGER :: I
INTEGER :: JLON, JLEV

IPZTMP = LOC (PSTACK (1))

DO JLEV = 0, KLEV
  DO JLON = KIDIA, KFDIA
    ZTMP (JLON, JLEV) = 1 + 1000 * JLEV + 10 * JLON
  ENDDO
ENDDO

END SUBROUTINE ACTKE
