PROGRAM MAIN_SIMPLE4_ACTKE

#ifdef GPU
#define ATTR_ARG , DEVICE
USE CUDAFOR
#else
#define ATTR_ARG
#endif

USE YOMLOG
USE LOAD_MOD
IMPLICIT NONE
INTEGER(KIND=JPIM)          :: KIDIA      
INTEGER(KIND=JPIM)          :: KFDIA      
INTEGER(KIND=JPIM)          :: KLON       
INTEGER(KIND=JPIM)          :: KTDIAT     
INTEGER(KIND=JPIM)          :: KTDIAN     
INTEGER(KIND=JPIM)          :: KLEV       
REAL(KIND=JPRB)   , POINTER :: PAPHI      (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPHIF     (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPRS      (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPRSF     (:, :)
REAL(KIND=JPRB)   , POINTER :: PDELP      (:, :)
REAL(KIND=JPRB)   , POINTER :: PR         (:, :)
REAL(KIND=JPRB)   , POINTER :: PT         (:, :)
REAL(KIND=JPRB)   , POINTER :: PU         (:, :)
REAL(KIND=JPRB)   , POINTER :: PV         (:, :)
REAL(KIND=JPRB)   , POINTER :: PQ         (:, :)
REAL(KIND=JPRB)   , POINTER :: PLSCPE     (:, :)
REAL(KIND=JPRB)   , POINTER :: PCD        (:)
REAL(KIND=JPRB)   , POINTER :: PCH        (:)
REAL(KIND=JPRB)   , POINTER :: PGZ0       (:)
REAL(KIND=JPRB)   , POINTER :: PTS        (:)
REAL(KIND=JPRB)   , POINTER :: PQS        (:)
REAL(KIND=JPRB)   , POINTER :: PQICE      (:, :)
REAL(KIND=JPRB)   , POINTER :: PQLI       (:, :)
REAL(KIND=JPRB)   , POINTER :: PECT       (:, :)
REAL(KIND=JPRB)   , POINTER :: PPRODTH    (:, :)
REAL(KIND=JPRB)   , POINTER :: PNLAB      (:, :)
REAL(KIND=JPRB)   , POINTER :: PNLABCVP   (:, :)
REAL(KIND=JPRB)   , POINTER :: PKTROV     (:, :)
REAL(KIND=JPRB)   , POINTER :: PKUROV     (:, :)
REAL(KIND=JPRB)   , POINTER :: PXTROV     (:, :)
REAL(KIND=JPRB)   , POINTER :: PXUROV     (:, :)
REAL(KIND=JPRB)   , POINTER :: PNBVNO     (:, :)
REAL(KIND=JPRB)   , POINTER :: PNEBS      (:, :)
REAL(KIND=JPRB)   , POINTER :: PQCS       (:, :)
REAL(KIND=JPRB)   , POINTER :: PNEBS0     (:, :)
REAL(KIND=JPRB)   , POINTER :: PQCS0      (:, :)
REAL(KIND=JPRB)   , POINTER :: PCOEFN     (:, :)
REAL(KIND=JPRB)   , POINTER :: PFECT      (:, :)
REAL(KIND=JPRB)   , POINTER :: PECT1      (:, :)
REAL(KIND=JPRB)   , POINTER :: PTPRDY     (:, :)
REAL(KIND=JPRB)   , POINTER :: PEDR       (:, :)
REAL(KIND=JPRB)             :: RG         
REAL(KIND=JPRB)             :: RPRTH      
REAL(KIND=JPRB)             :: ECTMIN     
REAL(KIND=JPRB)             :: TSPHY      
REAL(KIND=JPRB)             :: ACBRPHIM   
REAL(KIND=JPRB)             :: ADISE      
REAL(KIND=JPRB)             :: ADISI      
REAL(KIND=JPRB)             :: AKN        
REAL(KIND=JPRB)             :: ALD        
REAL(KIND=JPRB)             :: ALMAV      
REAL(KIND=JPRB)             :: ALMAVE     
REAL(KIND=JPRB)             :: ALMAVX     
REAL(KIND=JPRB)             :: ALPHAE     
REAL(KIND=JPRB)             :: ALPHAT     
REAL(KIND=JPRB)             :: ARSB2      
REAL(KIND=JPRB)             :: ARSC1      
REAL(KIND=JPRB)             :: ECTMAX     
REAL(KIND=JPRB)             :: EDB        
REAL(KIND=JPRB)             :: EDC        
REAL(KIND=JPRB)             :: EDD        
REAL(KIND=JPRB)             :: RALPD      
REAL(KIND=JPRB)             :: RALPS      
REAL(KIND=JPRB)             :: RALPW      
REAL(KIND=JPRB)             :: RATM       
REAL(KIND=JPRB)             :: RBETD      
REAL(KIND=JPRB)             :: RBETS      
REAL(KIND=JPRB)             :: RBETW      
REAL(KIND=JPRB)             :: RCPV       
REAL(KIND=JPRB)             :: RCS        
REAL(KIND=JPRB)             :: RCW        
REAL(KIND=JPRB)             :: RD         
REAL(KIND=JPRB)             :: RDT        
REAL(KIND=JPRB)             :: RETV       
REAL(KIND=JPRB)             :: RGAMD      
REAL(KIND=JPRB)             :: RGAMS      
REAL(KIND=JPRB)             :: RGAMW      
REAL(KIND=JPRB)             :: RKAPPA     
REAL(KIND=JPRB)             :: RLSTT      
REAL(KIND=JPRB)             :: RLVTT      
REAL(KIND=JPRB)             :: RTT        
REAL(KIND=JPRB)             :: RV         
REAL(KIND=JPRB)             :: UDECT      
REAL(KIND=JPRB)             :: UPRETMAX   
REAL(KIND=JPRB)             :: UPRETMIN   
REAL(KIND=JPRB)             :: USHEARM    
REAL(KIND=JPRB)             :: USURIC     
REAL(KIND=JPRB)             :: VKARMN     
INTEGER(KIND=JPIM)          :: KSIZST     
INTEGER(KIND=JPIM)          :: KPTRST     
REAL(KIND=JPRB)   , POINTER :: PSTACK     (:, :)
INTEGER(KIND=JPIM)          :: NGPBLKS    
INTEGER(KIND=JPIM)          :: KIDIA_1    
INTEGER(KIND=JPIM)          :: KFDIA_1    
INTEGER(KIND=JPIM)          :: KLON_1     
INTEGER(KIND=JPIM)          :: KTDIAT_1   
INTEGER(KIND=JPIM)          :: KTDIAN_1   
INTEGER(KIND=JPIM)          :: KLEV_1     
REAL(KIND=JPRB)   , POINTER :: PAPHI_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPHIF_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPRS_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPRSF_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PDELP_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PR_1       (:, :)
REAL(KIND=JPRB)   , POINTER :: PT_1       (:, :)
REAL(KIND=JPRB)   , POINTER :: PU_1       (:, :)
REAL(KIND=JPRB)   , POINTER :: PV_1       (:, :)
REAL(KIND=JPRB)   , POINTER :: PQ_1       (:, :)
REAL(KIND=JPRB)   , POINTER :: PLSCPE_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PCD_1      (:)
REAL(KIND=JPRB)   , POINTER :: PCH_1      (:)
REAL(KIND=JPRB)   , POINTER :: PGZ0_1     (:)
REAL(KIND=JPRB)   , POINTER :: PTS_1      (:)
REAL(KIND=JPRB)   , POINTER :: PQS_1      (:)
REAL(KIND=JPRB)   , POINTER :: PQICE_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PQLI_1     (:, :)
REAL(KIND=JPRB)   , POINTER :: PECT_1     (:, :)
REAL(KIND=JPRB)   , POINTER :: PPRODTH_1  (:, :)
REAL(KIND=JPRB)   , POINTER :: PNLAB_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PNLABCVP_1 (:, :)
REAL(KIND=JPRB)   , POINTER :: PKTROV_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PKUROV_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PXTROV_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PXUROV_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PNBVNO_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PNEBS_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PQCS_1     (:, :)
REAL(KIND=JPRB)   , POINTER :: PNEBS0_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PQCS0_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PCOEFN_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PFECT_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PECT1_1    (:, :)
REAL(KIND=JPRB)   , POINTER :: PTPRDY_1   (:, :)
REAL(KIND=JPRB)   , POINTER :: PEDR_1     (:, :)
REAL(KIND=JPRB)             :: RG_1       
REAL(KIND=JPRB)             :: RPRTH_1    
REAL(KIND=JPRB)             :: ECTMIN_1   
REAL(KIND=JPRB)             :: TSPHY_1    
REAL(KIND=JPRB)             :: ACBRPHIM_1 
REAL(KIND=JPRB)             :: ADISE_1    
REAL(KIND=JPRB)             :: ADISI_1    
REAL(KIND=JPRB)             :: AKN_1      
REAL(KIND=JPRB)             :: ALD_1      
REAL(KIND=JPRB)             :: ALMAV_1    
REAL(KIND=JPRB)             :: ALMAVE_1   
REAL(KIND=JPRB)             :: ALMAVX_1   
REAL(KIND=JPRB)             :: ALPHAE_1   
REAL(KIND=JPRB)             :: ALPHAT_1   
REAL(KIND=JPRB)             :: ARSB2_1    
REAL(KIND=JPRB)             :: ARSC1_1    
REAL(KIND=JPRB)             :: ECTMAX_1   
REAL(KIND=JPRB)             :: EDB_1      
REAL(KIND=JPRB)             :: EDC_1      
REAL(KIND=JPRB)             :: EDD_1      
REAL(KIND=JPRB)             :: RALPD_1    
REAL(KIND=JPRB)             :: RALPS_1    
REAL(KIND=JPRB)             :: RALPW_1    
REAL(KIND=JPRB)             :: RATM_1     
REAL(KIND=JPRB)             :: RBETD_1    
REAL(KIND=JPRB)             :: RBETS_1    
REAL(KIND=JPRB)             :: RBETW_1    
REAL(KIND=JPRB)             :: RCPV_1     
REAL(KIND=JPRB)             :: RCS_1      
REAL(KIND=JPRB)             :: RCW_1      
REAL(KIND=JPRB)             :: RD_1       
REAL(KIND=JPRB)             :: RDT_1      
REAL(KIND=JPRB)             :: RETV_1     
REAL(KIND=JPRB)             :: RGAMD_1    
REAL(KIND=JPRB)             :: RGAMS_1    
REAL(KIND=JPRB)             :: RGAMW_1    
REAL(KIND=JPRB)             :: RKAPPA_1   
REAL(KIND=JPRB)             :: RLSTT_1    
REAL(KIND=JPRB)             :: RLVTT_1    
REAL(KIND=JPRB)             :: RTT_1      
REAL(KIND=JPRB)             :: RV_1       
REAL(KIND=JPRB)             :: UDECT_1    
REAL(KIND=JPRB)             :: UPRETMAX_1 
REAL(KIND=JPRB)             :: UPRETMIN_1 
REAL(KIND=JPRB)             :: USHEARM_1  
REAL(KIND=JPRB)             :: USURIC_1   
REAL(KIND=JPRB)             :: VKARMN_1   
INTEGER(KIND=JPIM) ATTR_ARG :: KIDIA_2    
INTEGER(KIND=JPIM) ATTR_ARG :: KFDIA_2    
INTEGER(KIND=JPIM) ATTR_ARG :: KLON_2     
INTEGER(KIND=JPIM) ATTR_ARG :: KTDIAT_2   
INTEGER(KIND=JPIM) ATTR_ARG :: KTDIAN_2   
INTEGER(KIND=JPIM) ATTR_ARG :: KLEV_2     
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPHI_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPHIF_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPRS_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPRSF_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PDELP_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PR_2       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PT_2       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PU_2       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PV_2       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQ_2       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PLSCPE_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCD_2      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCH_2      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PGZ0_2     (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PTS_2      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQS_2      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQICE_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQLI_2     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PECT_2     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PPRODTH_2  (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNLAB_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNLABCVP_2 (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PKTROV_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PKUROV_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PXTROV_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PXUROV_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNBVNO_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNEBS_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQCS_2     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNEBS0_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQCS0_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCOEFN_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PFECT_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PECT1_2    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PTPRDY_2   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PEDR_2     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG          :: RG_2       
REAL(KIND=JPRB) ATTR_ARG          :: RPRTH_2    
REAL(KIND=JPRB) ATTR_ARG          :: ECTMIN_2   
REAL(KIND=JPRB) ATTR_ARG          :: TSPHY_2    
REAL(KIND=JPRB) ATTR_ARG          :: ACBRPHIM_2 
REAL(KIND=JPRB) ATTR_ARG          :: ADISE_2    
REAL(KIND=JPRB) ATTR_ARG          :: ADISI_2    
REAL(KIND=JPRB) ATTR_ARG          :: AKN_2      
REAL(KIND=JPRB) ATTR_ARG          :: ALD_2      
REAL(KIND=JPRB) ATTR_ARG          :: ALMAV_2    
REAL(KIND=JPRB) ATTR_ARG          :: ALMAVE_2   
REAL(KIND=JPRB) ATTR_ARG          :: ALMAVX_2   
REAL(KIND=JPRB) ATTR_ARG          :: ALPHAE_2   
REAL(KIND=JPRB) ATTR_ARG          :: ALPHAT_2   
REAL(KIND=JPRB) ATTR_ARG          :: ARSB2_2    
REAL(KIND=JPRB) ATTR_ARG          :: ARSC1_2    
REAL(KIND=JPRB) ATTR_ARG          :: ECTMAX_2   
REAL(KIND=JPRB) ATTR_ARG          :: EDB_2      
REAL(KIND=JPRB) ATTR_ARG          :: EDC_2      
REAL(KIND=JPRB) ATTR_ARG          :: EDD_2      
REAL(KIND=JPRB) ATTR_ARG          :: RALPD_2    
REAL(KIND=JPRB) ATTR_ARG          :: RALPS_2    
REAL(KIND=JPRB) ATTR_ARG          :: RALPW_2    
REAL(KIND=JPRB) ATTR_ARG          :: RATM_2     
REAL(KIND=JPRB) ATTR_ARG          :: RBETD_2    
REAL(KIND=JPRB) ATTR_ARG          :: RBETS_2    
REAL(KIND=JPRB) ATTR_ARG          :: RBETW_2    
REAL(KIND=JPRB) ATTR_ARG          :: RCPV_2     
REAL(KIND=JPRB) ATTR_ARG          :: RCS_2      
REAL(KIND=JPRB) ATTR_ARG          :: RCW_2      
REAL(KIND=JPRB) ATTR_ARG          :: RD_2       
REAL(KIND=JPRB) ATTR_ARG          :: RDT_2      
REAL(KIND=JPRB) ATTR_ARG          :: RETV_2     
REAL(KIND=JPRB) ATTR_ARG          :: RGAMD_2    
REAL(KIND=JPRB) ATTR_ARG          :: RGAMS_2    
REAL(KIND=JPRB) ATTR_ARG          :: RGAMW_2    
REAL(KIND=JPRB) ATTR_ARG          :: RKAPPA_2   
REAL(KIND=JPRB) ATTR_ARG          :: RLSTT_2    
REAL(KIND=JPRB) ATTR_ARG          :: RLVTT_2    
REAL(KIND=JPRB) ATTR_ARG          :: RTT_2      
REAL(KIND=JPRB) ATTR_ARG          :: RV_2       
REAL(KIND=JPRB) ATTR_ARG          :: UDECT_2    
REAL(KIND=JPRB) ATTR_ARG          :: UPRETMAX_2 
REAL(KIND=JPRB) ATTR_ARG          :: UPRETMIN_2 
REAL(KIND=JPRB) ATTR_ARG          :: USHEARM_2  
REAL(KIND=JPRB) ATTR_ARG          :: USURIC_2   
REAL(KIND=JPRB) ATTR_ARG          :: VKARMN_2   
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PSTACK_2 (:, :, :)
INTEGER(KIND=JPIM) ATTR_ARG       :: KSIZST_2
INTEGER(KIND=JPIM) ATTR_ARG       :: KPTRST_2
INTEGER(KIND=JPIM) ATTR_ARG       :: NGPBLKS_2
INTEGER :: IBLOCK
INTEGER :: ISTAT, II

INTEGER :: IFILE, ILINE, IIND
REAL :: ZVALUE

#ifdef GPU
TYPE (CUDAEVENT) :: STARTEVENT, STOPEVENT
#endif
REAL :: TIME

#include "run_simple4_actke.intfb.h"


ALLOCATE (IPTR (1), NFILE (2000), NLINE (2000), NIND (2000), RVALUE (2000))
IPTR (1) = 0
DO II = 1, 2000
NFILE (II) = 0
NLINE (II) = 0
RVALUE (II) = -999.999
ENDDO

OPEN (ILUNC, FILE="ACTKE.COUNT", FORM="FORMATTED")
READ (ILUNC, *) NGPBLKS
CLOSE (ILUNC)
CALL OPEN_LOAD ("ACTKE")
DO IBLOCK = 1, NGPBLKS
  CALL LOAD (ILUN_IN, KIDIA)
  CALL LOAD (ILUN_IN, KFDIA)
  CALL LOAD (ILUN_IN, KLON)
  CALL LOAD (ILUN_IN, KTDIAT)
  CALL LOAD (ILUN_IN, KTDIAN)
  CALL LOAD (ILUN_IN, KLEV)
  CALL LOAD (ILUN_IN, PAPHI)
  CALL LOAD (ILUN_IN, PAPHIF)
  CALL LOAD (ILUN_IN, PAPRS)
  CALL LOAD (ILUN_IN, PAPRSF)
  CALL LOAD (ILUN_IN, PDELP)
  CALL LOAD (ILUN_IN, PR)
  CALL LOAD (ILUN_IN, PT)
  CALL LOAD (ILUN_IN, PU)
  CALL LOAD (ILUN_IN, PV)
  CALL LOAD (ILUN_IN, PQ)
  CALL LOAD (ILUN_IN, PLSCPE)
  CALL LOAD (ILUN_IN, PCD)
  CALL LOAD (ILUN_IN, PCH)
  CALL LOAD (ILUN_IN, PGZ0)
  CALL LOAD (ILUN_IN, PTS)
  CALL LOAD (ILUN_IN, PQS)
  CALL LOAD (ILUN_IN, PQICE)
  CALL LOAD (ILUN_IN, PQLI)
  CALL LOAD (ILUN_IN, PECT)
  CALL LOAD (ILUN_IN, PPRODTH)
  CALL LOAD (ILUN_IN, PNLAB)
  CALL LOAD (ILUN_IN, PNLABCVP)
  CALL LOAD (ILUN_IN, PKTROV)
  CALL LOAD (ILUN_IN, PKUROV)
  CALL LOAD (ILUN_IN, PXTROV)
  CALL LOAD (ILUN_IN, PXUROV)
  CALL LOAD (ILUN_IN, PNBVNO)
  CALL LOAD (ILUN_IN, PNEBS)
  CALL LOAD (ILUN_IN, PQCS)
  CALL LOAD (ILUN_IN, PNEBS0)
  CALL LOAD (ILUN_IN, PQCS0)
  CALL LOAD (ILUN_IN, PCOEFN)
  CALL LOAD (ILUN_IN, PFECT)
  CALL LOAD (ILUN_IN, PECT1)
  CALL LOAD (ILUN_IN, PTPRDY)
  CALL LOAD (ILUN_IN, PEDR)
  CALL LOAD (ILUN_IN, RG)
  CALL LOAD (ILUN_IN, RPRTH)
  CALL LOAD (ILUN_IN, ECTMIN)
  CALL LOAD (ILUN_IN, TSPHY)
  CALL LOAD (ILUN_IN, ACBRPHIM)
  CALL LOAD (ILUN_IN, ADISE)
  CALL LOAD (ILUN_IN, ADISI)
  CALL LOAD (ILUN_IN, AKN)
  CALL LOAD (ILUN_IN, ALD)
  CALL LOAD (ILUN_IN, ALMAV)
  CALL LOAD (ILUN_IN, ALMAVE)
  CALL LOAD (ILUN_IN, ALMAVX)
  CALL LOAD (ILUN_IN, ALPHAE)
  CALL LOAD (ILUN_IN, ALPHAT)
  CALL LOAD (ILUN_IN, ARSB2)
  CALL LOAD (ILUN_IN, ARSC1)
  CALL LOAD (ILUN_IN, ECTMAX)
  CALL LOAD (ILUN_IN, EDB)
  CALL LOAD (ILUN_IN, EDC)
  CALL LOAD (ILUN_IN, EDD)
  CALL LOAD (ILUN_IN, RALPD)
  CALL LOAD (ILUN_IN, RALPS)
  CALL LOAD (ILUN_IN, RALPW)
  CALL LOAD (ILUN_IN, RATM)
  CALL LOAD (ILUN_IN, RBETD)
  CALL LOAD (ILUN_IN, RBETS)
  CALL LOAD (ILUN_IN, RBETW)
  CALL LOAD (ILUN_IN, RCPV)
  CALL LOAD (ILUN_IN, RCS)
  CALL LOAD (ILUN_IN, RCW)
  CALL LOAD (ILUN_IN, RD)
  CALL LOAD (ILUN_IN, RDT)
  CALL LOAD (ILUN_IN, RETV)
  CALL LOAD (ILUN_IN, RGAMD)
  CALL LOAD (ILUN_IN, RGAMS)
  CALL LOAD (ILUN_IN, RGAMW)
  CALL LOAD (ILUN_IN, RKAPPA)
  CALL LOAD (ILUN_IN, RLSTT)
  CALL LOAD (ILUN_IN, RLVTT)
  CALL LOAD (ILUN_IN, RTT)
  CALL LOAD (ILUN_IN, RV)
  CALL LOAD (ILUN_IN, UDECT)
  CALL LOAD (ILUN_IN, UPRETMAX)
  CALL LOAD (ILUN_IN, UPRETMIN)
  CALL LOAD (ILUN_IN, USHEARM)
  CALL LOAD (ILUN_IN, USURIC)
  CALL LOAD (ILUN_IN, VKARMN)
  IF (IBLOCK == 1) THEN
    ALLOCATE (PAPHI_2 (KLON, LBOUND (PAPHI, 2):UBOUND (PAPHI, 2), NGPBLKS))
    ALLOCATE (PAPHIF_2 (KLON, LBOUND (PAPHIF, 2):UBOUND (PAPHIF, 2), NGPBLKS))
    ALLOCATE (PAPRS_2 (KLON, LBOUND (PAPRS, 2):UBOUND (PAPRS, 2), NGPBLKS))
    ALLOCATE (PAPRSF_2 (KLON, LBOUND (PAPRSF, 2):UBOUND (PAPRSF, 2), NGPBLKS))
    ALLOCATE (PDELP_2 (KLON, LBOUND (PDELP, 2):UBOUND (PDELP, 2), NGPBLKS))
    ALLOCATE (PR_2 (KLON, LBOUND (PR, 2):UBOUND (PR, 2), NGPBLKS))
    ALLOCATE (PT_2 (KLON, LBOUND (PT, 2):UBOUND (PT, 2), NGPBLKS))
    ALLOCATE (PU_2 (KLON, LBOUND (PU, 2):UBOUND (PU, 2), NGPBLKS))
    ALLOCATE (PV_2 (KLON, LBOUND (PV, 2):UBOUND (PV, 2), NGPBLKS))
    ALLOCATE (PQ_2 (KLON, LBOUND (PQ, 2):UBOUND (PQ, 2), NGPBLKS))
    ALLOCATE (PLSCPE_2 (KLON, LBOUND (PLSCPE, 2):UBOUND (PLSCPE, 2), NGPBLKS))
    ALLOCATE (PCD_2 (KLON, NGPBLKS))
    ALLOCATE (PCH_2 (KLON, NGPBLKS))
    ALLOCATE (PGZ0_2 (KLON, NGPBLKS))
    ALLOCATE (PTS_2 (KLON, NGPBLKS))
    ALLOCATE (PQS_2 (KLON, NGPBLKS))
    ALLOCATE (PQICE_2 (KLON, LBOUND (PQICE, 2):UBOUND (PQICE, 2), NGPBLKS))
    ALLOCATE (PQLI_2 (KLON, LBOUND (PQLI, 2):UBOUND (PQLI, 2), NGPBLKS))
    ALLOCATE (PECT_2 (KLON, LBOUND (PECT, 2):UBOUND (PECT, 2), NGPBLKS))
    ALLOCATE (PPRODTH_2 (KLON, LBOUND (PPRODTH, 2):UBOUND (PPRODTH, 2), NGPBLKS)&
    & )
    ALLOCATE (PNLAB_2 (KLON, LBOUND (PNLAB, 2):UBOUND (PNLAB, 2), NGPBLKS))
    ALLOCATE (PNLABCVP_2 (KLON, LBOUND (PNLABCVP, 2):UBOUND (PNLABCVP, 2), &
    & NGPBLKS))
    ALLOCATE (PKTROV_2 (KLON, LBOUND (PKTROV, 2):UBOUND (PKTROV, 2), NGPBLKS))
    ALLOCATE (PKUROV_2 (KLON, LBOUND (PKUROV, 2):UBOUND (PKUROV, 2), NGPBLKS))
    ALLOCATE (PXTROV_2 (KLON, LBOUND (PXTROV, 2):UBOUND (PXTROV, 2), NGPBLKS))
    ALLOCATE (PXUROV_2 (KLON, LBOUND (PXUROV, 2):UBOUND (PXUROV, 2), NGPBLKS))
    ALLOCATE (PNBVNO_2 (KLON, LBOUND (PNBVNO, 2):UBOUND (PNBVNO, 2), NGPBLKS))
    ALLOCATE (PNEBS_2 (KLON, LBOUND (PNEBS, 2):UBOUND (PNEBS, 2), NGPBLKS))
    ALLOCATE (PQCS_2 (KLON, LBOUND (PQCS, 2):UBOUND (PQCS, 2), NGPBLKS))
    ALLOCATE (PNEBS0_2 (KLON, LBOUND (PNEBS0, 2):UBOUND (PNEBS0, 2), NGPBLKS))
    ALLOCATE (PQCS0_2 (KLON, LBOUND (PQCS0, 2):UBOUND (PQCS0, 2), NGPBLKS))
    ALLOCATE (PCOEFN_2 (KLON, LBOUND (PCOEFN, 2):UBOUND (PCOEFN, 2), NGPBLKS))
    ALLOCATE (PFECT_2 (KLON, LBOUND (PFECT, 2):UBOUND (PFECT, 2), NGPBLKS))
    ALLOCATE (PECT1_2 (KLON, LBOUND (PECT1, 2):UBOUND (PECT1, 2), NGPBLKS))
    ALLOCATE (PTPRDY_2 (KLON, LBOUND (PTPRDY, 2):UBOUND (PTPRDY, 2), NGPBLKS))
    ALLOCATE (PEDR_2 (KLON, LBOUND (PEDR, 2):UBOUND (PEDR, 2), NGPBLKS))
  ENDIF
  PAPHI_2 (:, :, IBLOCK) = PAPHI
  PAPHIF_2 (:, :, IBLOCK) = PAPHIF
  PAPRS_2 (:, :, IBLOCK) = PAPRS
  PAPRSF_2 (:, :, IBLOCK) = PAPRSF
  PDELP_2 (:, :, IBLOCK) = PDELP
  PR_2 (:, :, IBLOCK) = PR
  PT_2 (:, :, IBLOCK) = PT
  PU_2 (:, :, IBLOCK) = PU
  PV_2 (:, :, IBLOCK) = PV
  PQ_2 (:, :, IBLOCK) = PQ
  PLSCPE_2 (:, :, IBLOCK) = PLSCPE
  PCD_2 (:, IBLOCK) = PCD
  PCH_2 (:, IBLOCK) = PCH
  PGZ0_2 (:, IBLOCK) = PGZ0
  PTS_2 (:, IBLOCK) = PTS
  PQS_2 (:, IBLOCK) = PQS
  PQICE_2 (:, :, IBLOCK) = PQICE
  PQLI_2 (:, :, IBLOCK) = PQLI
  PECT_2 (:, :, IBLOCK) = PECT
  PPRODTH_2 (:, :, IBLOCK) = PPRODTH
  PNLAB_2 (:, :, IBLOCK) = PNLAB
  PNLABCVP_2 (:, :, IBLOCK) = PNLABCVP
  PKTROV_2 (:, :, IBLOCK) = PKTROV
  PKUROV_2 (:, :, IBLOCK) = PKUROV
  PXTROV_2 (:, :, IBLOCK) = PXTROV
  PXUROV_2 (:, :, IBLOCK) = PXUROV
  PNBVNO_2 (:, :, IBLOCK) = PNBVNO
  PNEBS_2 (:, :, IBLOCK) = PNEBS
  PQCS_2 (:, :, IBLOCK) = PQCS
  PNEBS0_2 (:, :, IBLOCK) = PNEBS0
  PQCS0_2 (:, :, IBLOCK) = PQCS0
  PCOEFN_2 (:, :, IBLOCK) = PCOEFN
  PFECT_2 (:, :, IBLOCK) = PFECT
  PECT1_2 (:, :, IBLOCK) = PECT1
  PTPRDY_2 (:, :, IBLOCK) = PTPRDY
  PEDR_2 (:, :, IBLOCK) = PEDR
  DEALLOCATE (PAPHI)
  DEALLOCATE (PAPHIF)
  DEALLOCATE (PAPRS)
  DEALLOCATE (PAPRSF)
  DEALLOCATE (PDELP)
  DEALLOCATE (PR)
  DEALLOCATE (PT)
  DEALLOCATE (PU)
  DEALLOCATE (PV)
  DEALLOCATE (PQ)
  DEALLOCATE (PLSCPE)
  DEALLOCATE (PCD)
  DEALLOCATE (PCH)
  DEALLOCATE (PGZ0)
  DEALLOCATE (PTS)
  DEALLOCATE (PQS)
  DEALLOCATE (PQICE)
  DEALLOCATE (PQLI)
  DEALLOCATE (PECT)
  DEALLOCATE (PPRODTH)
  DEALLOCATE (PNLAB)
  DEALLOCATE (PNLABCVP)
  DEALLOCATE (PKTROV)
  DEALLOCATE (PKUROV)
  DEALLOCATE (PXTROV)
  DEALLOCATE (PXUROV)
  DEALLOCATE (PNBVNO)
  DEALLOCATE (PNEBS)
  DEALLOCATE (PQCS)
  DEALLOCATE (PNEBS0)
  DEALLOCATE (PQCS0)
  DEALLOCATE (PCOEFN)
  DEALLOCATE (PFECT)
  DEALLOCATE (PECT1)
  DEALLOCATE (PTPRDY)
  DEALLOCATE (PEDR)
ENDDO
CALL CLOSE_LOAD
KSIZST = 21 * KLEV + 10
KPTRST = 1
ALLOCATE (PSTACK_2 (KLON, KSIZST, NGPBLKS))
KIDIA = 1
KFDIA = KLON
KIDIA_2 = KIDIA
KFDIA_2 = KFDIA
KLON_2 = KLON
KTDIAT_2 = KTDIAT
KTDIAN_2 = KTDIAN
KLEV_2 = KLEV
RG_2 = RG
RPRTH_2 = RPRTH
ECTMIN_2 = ECTMIN
TSPHY_2 = TSPHY
ACBRPHIM_2 = ACBRPHIM
ADISE_2 = ADISE
ADISI_2 = ADISI
AKN_2 = AKN
ALD_2 = ALD
ALMAV_2 = ALMAV
ALMAVE_2 = ALMAVE
ALMAVX_2 = ALMAVX
ALPHAE_2 = ALPHAE
ALPHAT_2 = ALPHAT
ARSB2_2 = ARSB2
ARSC1_2 = ARSC1
ECTMAX_2 = ECTMAX
EDB_2 = EDB
EDC_2 = EDC
EDD_2 = EDD
RALPD_2 = RALPD
RALPS_2 = RALPS
RALPW_2 = RALPW
RATM_2 = RATM
RBETD_2 = RBETD
RBETS_2 = RBETS
RBETW_2 = RBETW
RCPV_2 = RCPV
RCS_2 = RCS
RCW_2 = RCW
RD_2 = RD
RDT_2 = RDT
RETV_2 = RETV
RGAMD_2 = RGAMD
RGAMS_2 = RGAMS
RGAMW_2 = RGAMW
RKAPPA_2 = RKAPPA
RLSTT_2 = RLSTT
RLVTT_2 = RLVTT
RTT_2 = RTT
RV_2 = RV
UDECT_2 = UDECT
UPRETMAX_2 = UPRETMAX
UPRETMIN_2 = UPRETMIN
USHEARM_2 = USHEARM
USURIC_2 = USURIC
VKARMN_2 = VKARMN
KSIZST_2 = KSIZST
KPTRST_2 = KPTRST
NGPBLKS_2 = NGPBLKS


#ifdef GPU
ISTAT = CUDAEVENTCREATE (STARTEVENT)
ISTAT = CUDAEVENTCREATE (STOPEVENT)
ISTAT = CUDAEVENTRECORD (STARTEVENT, 0)

CALL RUN_SIMPLE4_ACTKE <<<NGPBLKS, KLON>>> &
#else
CALL RUN_SIMPLE4_ACTKE &
#endif
&                      (KIDIA_2, KFDIA_2, KLON_2, KTDIAT_2, KTDIAN_2, KLEV_2,   &
& PAPHI_2, PAPHIF_2, PAPRS_2, PAPRSF_2, PDELP_2, PR_2, PT_2, PU_2, PV_2, PQ_2,  &
& PLSCPE_2, PCD_2, PCH_2, PGZ0_2, PTS_2, PQS_2, PQICE_2, PQLI_2, PECT_2,        &
& PPRODTH_2, PNLAB_2, PNLABCVP_2, PKTROV_2, PKUROV_2, PXTROV_2, PXUROV_2,       &
& PNBVNO_2, PNEBS_2, PQCS_2, PNEBS0_2, PQCS0_2, PCOEFN_2, PFECT_2, PECT1_2,     &
& PTPRDY_2, PEDR_2, RG_2, RPRTH_2, ECTMIN_2, TSPHY_2, ACBRPHIM_2, ADISE_2,      &
& ADISI_2, AKN_2, ALD_2, ALMAV_2, ALMAVE_2, ALMAVX_2, ALPHAE_2, ALPHAT_2,       &
& ARSB2_2, ARSC1_2, ECTMAX_2, EDB_2, EDC_2, EDD_2, RALPD_2, RALPS_2, RALPW_2,   &
& RATM_2, RBETD_2, RBETS_2, RBETW_2, RCPV_2, RCS_2, RCW_2, RD_2, RDT_2, RETV_2, &
& RGAMD_2, RGAMS_2, RGAMW_2, RKAPPA_2, RLSTT_2, RLVTT_2, RTT_2, RV_2, UDECT_2,  &
& UPRETMAX_2, UPRETMIN_2, USHEARM_2, USURIC_2, VKARMN_2, KSIZST_2, KPTRST_2,    &
& PSTACK_2, NGPBLKS_2)

#ifdef GPU
ISTAT = CUDAEVENTRECORD (STOPEVENT, 0)
ISTAT = CUDAEVENTSYNCHRONIZE (STOPEVENT)
ISTAT = CUDAEVENTELAPSEDTIME (TIME, STARTEVENT, STOPEVENT)

PRINT *, " TIME = ", TIME

#else

PRINT *

#endif


#ifdef UNDEF
WRITE (0, *) __FILE__, ':', __LINE__ 

DO II = 1, 2000
  IFILE = NFILE  (II)
  IF (IFILE == 0) EXIT
  ILINE  = NLINE  (II)
  IIND   = NIND   (II)
  ZVALUE = RVALUE (II)
  WRITE (*, '(A,":",I0," ",I6," ",E20.12)') CHAR (IFILE), ILINE, IIND, ZVALUE
ENDDO
#endif


!ifdef UNDEF

CALL OPEN_LOAD ("ACTKE")
ALLOCATE (PAPHI (KLON, LBOUND (PAPHI_2, 2):UBOUND (PAPHI_2, 2)))
ALLOCATE (PAPHIF (KLON, LBOUND (PAPHIF_2, 2):UBOUND (PAPHIF_2, 2)))
ALLOCATE (PAPRS (KLON, LBOUND (PAPRS_2, 2):UBOUND (PAPRS_2, 2)))
ALLOCATE (PAPRSF (KLON, LBOUND (PAPRSF_2, 2):UBOUND (PAPRSF_2, 2)))
ALLOCATE (PDELP (KLON, LBOUND (PDELP_2, 2):UBOUND (PDELP_2, 2)))
ALLOCATE (PR (KLON, LBOUND (PR_2, 2):UBOUND (PR_2, 2)))
ALLOCATE (PT (KLON, LBOUND (PT_2, 2):UBOUND (PT_2, 2)))
ALLOCATE (PU (KLON, LBOUND (PU_2, 2):UBOUND (PU_2, 2)))
ALLOCATE (PV (KLON, LBOUND (PV_2, 2):UBOUND (PV_2, 2)))
ALLOCATE (PQ (KLON, LBOUND (PQ_2, 2):UBOUND (PQ_2, 2)))
ALLOCATE (PLSCPE (KLON, LBOUND (PLSCPE_2, 2):UBOUND (PLSCPE_2, 2)))
ALLOCATE (PCD (KLON))
ALLOCATE (PCH (KLON))
ALLOCATE (PGZ0 (KLON))
ALLOCATE (PTS (KLON))
ALLOCATE (PQS (KLON))
ALLOCATE (PQICE (KLON, LBOUND (PQICE_2, 2):UBOUND (PQICE_2, 2)))
ALLOCATE (PQLI (KLON, LBOUND (PQLI_2, 2):UBOUND (PQLI_2, 2)))
ALLOCATE (PECT (KLON, LBOUND (PECT_2, 2):UBOUND (PECT_2, 2)))
ALLOCATE (PPRODTH (KLON, LBOUND (PPRODTH_2, 2):UBOUND (PPRODTH_2, 2)))
ALLOCATE (PNLAB (KLON, LBOUND (PNLAB_2, 2):UBOUND (PNLAB_2, 2)))
ALLOCATE (PNLABCVP (KLON, LBOUND (PNLABCVP_2, 2):UBOUND (PNLABCVP_2, 2)))
ALLOCATE (PKTROV (KLON, LBOUND (PKTROV_2, 2):UBOUND (PKTROV_2, 2)))
ALLOCATE (PKUROV (KLON, LBOUND (PKUROV_2, 2):UBOUND (PKUROV_2, 2)))
ALLOCATE (PXTROV (KLON, LBOUND (PXTROV_2, 2):UBOUND (PXTROV_2, 2)))
ALLOCATE (PXUROV (KLON, LBOUND (PXUROV_2, 2):UBOUND (PXUROV_2, 2)))
ALLOCATE (PNBVNO (KLON, LBOUND (PNBVNO_2, 2):UBOUND (PNBVNO_2, 2)))
ALLOCATE (PNEBS (KLON, LBOUND (PNEBS_2, 2):UBOUND (PNEBS_2, 2)))
ALLOCATE (PQCS (KLON, LBOUND (PQCS_2, 2):UBOUND (PQCS_2, 2)))
ALLOCATE (PNEBS0 (KLON, LBOUND (PNEBS0_2, 2):UBOUND (PNEBS0_2, 2)))
ALLOCATE (PQCS0 (KLON, LBOUND (PQCS0_2, 2):UBOUND (PQCS0_2, 2)))
ALLOCATE (PCOEFN (KLON, LBOUND (PCOEFN_2, 2):UBOUND (PCOEFN_2, 2)))
ALLOCATE (PFECT (KLON, LBOUND (PFECT_2, 2):UBOUND (PFECT_2, 2)))
ALLOCATE (PECT1 (KLON, LBOUND (PECT1_2, 2):UBOUND (PECT1_2, 2)))
ALLOCATE (PTPRDY (KLON, LBOUND (PTPRDY_2, 2):UBOUND (PTPRDY_2, 2)))
ALLOCATE (PEDR (KLON, LBOUND (PEDR_2, 2):UBOUND (PEDR_2, 2)))

!DO IBLOCK = 1, NGPBLKS
DO IBLOCK = 1, 10
  WRITE (*, *) "---", IBLOCK

  PAPHI    =  PAPHI_2 (:, :, IBLOCK)                                
  PAPHIF   =  PAPHIF_2 (:, :, IBLOCK)                               
  PAPRS    =  PAPRS_2 (:, :, IBLOCK)                                
  PAPRSF   =  PAPRSF_2 (:, :, IBLOCK)                               
  PDELP    =  PDELP_2 (:, :, IBLOCK)                                
  PR       =  PR_2 (:, :, IBLOCK)                                   
  PT       =  PT_2 (:, :, IBLOCK)                                   
  PU       =  PU_2 (:, :, IBLOCK)                                   
  PV       =  PV_2 (:, :, IBLOCK)                                   
  PQ       =  PQ_2 (:, :, IBLOCK)                                   
  PLSCPE   =  PLSCPE_2 (:, :, IBLOCK)                               
  PCD      =  PCD_2 (:, IBLOCK)                                     
  PCH      =  PCH_2 (:, IBLOCK)                                     
  PGZ0     =  PGZ0_2 (:, IBLOCK)                                    
  PTS      =  PTS_2 (:, IBLOCK)                                     
  PQS      =  PQS_2 (:, IBLOCK)                                     
  PQICE    =  PQICE_2 (:, :, IBLOCK)                                
  PQLI     =  PQLI_2 (:, :, IBLOCK)                                 
  PECT     =  PECT_2 (:, :, IBLOCK)                                 
  PPRODTH  =  PPRODTH_2 (:, :, IBLOCK)                              
  PNLAB    =  PNLAB_2 (:, :, IBLOCK)                                
  PNLABCVP =  PNLABCVP_2 (:, :, IBLOCK)                             
  PKTROV   =  PKTROV_2 (:, :, IBLOCK)                               
  PKUROV   =  PKUROV_2 (:, :, IBLOCK)                               
  PXTROV   =  PXTROV_2 (:, :, IBLOCK)                               
  PXUROV   =  PXUROV_2 (:, :, IBLOCK)                               
  PNBVNO   =  PNBVNO_2 (:, :, IBLOCK)                               
  PNEBS    =  PNEBS_2 (:, :, IBLOCK)                                
  PQCS     =  PQCS_2 (:, :, IBLOCK)                                 
  PNEBS0   =  PNEBS0_2 (:, :, IBLOCK)                               
  PQCS0    =  PQCS0_2 (:, :, IBLOCK)                                
  PCOEFN   =  PCOEFN_2 (:, :, IBLOCK)                               
  PFECT    =  PFECT_2 (:, :, IBLOCK)                                
  PECT1    =  PECT1_2 (:, :, IBLOCK)                                
  PTPRDY   =  PTPRDY_2 (:, :, IBLOCK)                               
  PEDR     =  PEDR_2 (:, :, IBLOCK)                                 

  CALL LOAD (ILUN_OUT, KIDIA_1)
  CALL LOAD (ILUN_OUT, KFDIA_1)
  CALL LOAD (ILUN_OUT, KLON_1)
  CALL LOAD (ILUN_OUT, KTDIAT_1)
  CALL LOAD (ILUN_OUT, KTDIAN_1)
  CALL LOAD (ILUN_OUT, KLEV_1)
  CALL LOAD (ILUN_OUT, PAPHI_1)
  CALL LOAD (ILUN_OUT, PAPHIF_1)
  CALL LOAD (ILUN_OUT, PAPRS_1)
  CALL LOAD (ILUN_OUT, PAPRSF_1)
  CALL LOAD (ILUN_OUT, PDELP_1)
  CALL LOAD (ILUN_OUT, PR_1)
  CALL LOAD (ILUN_OUT, PT_1)
  CALL LOAD (ILUN_OUT, PU_1)
  CALL LOAD (ILUN_OUT, PV_1)
  CALL LOAD (ILUN_OUT, PQ_1)
  CALL LOAD (ILUN_OUT, PLSCPE_1)
  CALL LOAD (ILUN_OUT, PCD_1)
  CALL LOAD (ILUN_OUT, PCH_1)
  CALL LOAD (ILUN_OUT, PGZ0_1)
  CALL LOAD (ILUN_OUT, PTS_1)
  CALL LOAD (ILUN_OUT, PQS_1)
  CALL LOAD (ILUN_OUT, PQICE_1)
  CALL LOAD (ILUN_OUT, PQLI_1)
  CALL LOAD (ILUN_OUT, PECT_1)
  CALL LOAD (ILUN_OUT, PPRODTH_1)
  CALL LOAD (ILUN_OUT, PNLAB_1)
  CALL LOAD (ILUN_OUT, PNLABCVP_1)
  CALL LOAD (ILUN_OUT, PKTROV_1)
  CALL LOAD (ILUN_OUT, PKUROV_1)
  CALL LOAD (ILUN_OUT, PXTROV_1)
  CALL LOAD (ILUN_OUT, PXUROV_1)
  CALL LOAD (ILUN_OUT, PNBVNO_1)
  CALL LOAD (ILUN_OUT, PNEBS_1)
  CALL LOAD (ILUN_OUT, PQCS_1)
  CALL LOAD (ILUN_OUT, PNEBS0_1)
  CALL LOAD (ILUN_OUT, PQCS0_1)
  CALL LOAD (ILUN_OUT, PCOEFN_1)
  CALL LOAD (ILUN_OUT, PFECT_1)
  CALL LOAD (ILUN_OUT, PECT1_1)
  CALL LOAD (ILUN_OUT, PTPRDY_1)
  CALL LOAD (ILUN_OUT, PEDR_1)
  CALL LOAD (ILUN_OUT, RG_1)
  CALL LOAD (ILUN_OUT, RPRTH_1)
  CALL LOAD (ILUN_OUT, ECTMIN_1)
  CALL LOAD (ILUN_OUT, TSPHY_1)
  CALL LOAD (ILUN_OUT, ACBRPHIM_1)
  CALL LOAD (ILUN_OUT, ADISE_1)
  CALL LOAD (ILUN_OUT, ADISI_1)
  CALL LOAD (ILUN_OUT, AKN_1)
  CALL LOAD (ILUN_OUT, ALD_1)
  CALL LOAD (ILUN_OUT, ALMAV_1)
  CALL LOAD (ILUN_OUT, ALMAVE_1)
  CALL LOAD (ILUN_OUT, ALMAVX_1)
  CALL LOAD (ILUN_OUT, ALPHAE_1)
  CALL LOAD (ILUN_OUT, ALPHAT_1)
  CALL LOAD (ILUN_OUT, ARSB2_1)
  CALL LOAD (ILUN_OUT, ARSC1_1)
  CALL LOAD (ILUN_OUT, ECTMAX_1)
  CALL LOAD (ILUN_OUT, EDB_1)
  CALL LOAD (ILUN_OUT, EDC_1)
  CALL LOAD (ILUN_OUT, EDD_1)
  CALL LOAD (ILUN_OUT, RALPD_1)
  CALL LOAD (ILUN_OUT, RALPS_1)
  CALL LOAD (ILUN_OUT, RALPW_1)
  CALL LOAD (ILUN_OUT, RATM_1)
  CALL LOAD (ILUN_OUT, RBETD_1)
  CALL LOAD (ILUN_OUT, RBETS_1)
  CALL LOAD (ILUN_OUT, RBETW_1)
  CALL LOAD (ILUN_OUT, RCPV_1)
  CALL LOAD (ILUN_OUT, RCS_1)
  CALL LOAD (ILUN_OUT, RCW_1)
  CALL LOAD (ILUN_OUT, RD_1)
  CALL LOAD (ILUN_OUT, RDT_1)
  CALL LOAD (ILUN_OUT, RETV_1)
  CALL LOAD (ILUN_OUT, RGAMD_1)
  CALL LOAD (ILUN_OUT, RGAMS_1)
  CALL LOAD (ILUN_OUT, RGAMW_1)
  CALL LOAD (ILUN_OUT, RKAPPA_1)
  CALL LOAD (ILUN_OUT, RLSTT_1)
  CALL LOAD (ILUN_OUT, RLVTT_1)
  CALL LOAD (ILUN_OUT, RTT_1)
  CALL LOAD (ILUN_OUT, RV_1)
  CALL LOAD (ILUN_OUT, UDECT_1)
  CALL LOAD (ILUN_OUT, UPRETMAX_1)
  CALL LOAD (ILUN_OUT, UPRETMIN_1)
  CALL LOAD (ILUN_OUT, USHEARM_1)
  CALL LOAD (ILUN_OUT, USURIC_1)
  CALL LOAD (ILUN_OUT, VKARMN_1)

  IF (KFDIA_1 == KLON_1) THEN ! Skip incomplete blocks
    CALL DIFF ("PAPHI", PAPHI, PAPHI_1)
    CALL DIFF ("PAPHIF", PAPHIF, PAPHIF_1)
    CALL DIFF ("PAPRS", PAPRS, PAPRS_1)
    CALL DIFF ("PAPRSF", PAPRSF, PAPRSF_1)
    CALL DIFF ("PDELP", PDELP, PDELP_1)
    CALL DIFF ("PR", PR, PR_1)
    CALL DIFF ("PT", PT, PT_1)
    CALL DIFF ("PU", PU, PU_1)
    CALL DIFF ("PV", PV, PV_1)
    CALL DIFF ("PQ", PQ, PQ_1)
    CALL DIFF ("PLSCPE", PLSCPE, PLSCPE_1)
    CALL DIFF ("PCD", PCD, PCD_1)
    CALL DIFF ("PCH", PCH, PCH_1)
    CALL DIFF ("PGZ0", PGZ0, PGZ0_1)
    CALL DIFF ("PTS", PTS, PTS_1)
    CALL DIFF ("PQS", PQS, PQS_1)
    CALL DIFF ("PQICE", PQICE, PQICE_1)
    CALL DIFF ("PQLI", PQLI, PQLI_1)
    CALL DIFF ("PECT", PECT, PECT_1)
    CALL DIFF ("PPRODTH", PPRODTH, PPRODTH_1)
    CALL DIFF ("PNLAB", PNLAB, PNLAB_1)
    CALL DIFF ("PNLABCVP", PNLABCVP, PNLABCVP_1)
    CALL DIFF ("PKTROV", PKTROV, PKTROV_1)
    CALL DIFF ("PKUROV", PKUROV, PKUROV_1)
    CALL DIFF ("PXTROV", PXTROV, PXTROV_1)
    CALL DIFF ("PXUROV", PXUROV, PXUROV_1)
    CALL DIFF ("PNBVNO", PNBVNO, PNBVNO_1)
    CALL DIFF ("PNEBS", PNEBS, PNEBS_1)
    CALL DIFF ("PQCS", PQCS, PQCS_1)
    CALL DIFF ("PNEBS0", PNEBS0, PNEBS0_1)
    CALL DIFF ("PQCS0", PQCS0, PQCS0_1)
    CALL DIFF ("PCOEFN", PCOEFN, PCOEFN_1)
    CALL DIFF ("PFECT", PFECT, PFECT_1)
    CALL DIFF ("PECT1", PECT1, PECT1_1)
    CALL DIFF ("PTPRDY", PTPRDY, PTPRDY_1)
    CALL DIFF ("PEDR", PEDR, PEDR_1)
  ENDIF
  DEALLOCATE (PAPHI_1)
  DEALLOCATE (PAPHIF_1)
  DEALLOCATE (PAPRS_1)
  DEALLOCATE (PAPRSF_1)
  DEALLOCATE (PDELP_1)
  DEALLOCATE (PR_1)
  DEALLOCATE (PT_1)
  DEALLOCATE (PU_1)
  DEALLOCATE (PV_1)
  DEALLOCATE (PQ_1)
  DEALLOCATE (PLSCPE_1)
  DEALLOCATE (PCD_1)
  DEALLOCATE (PCH_1)
  DEALLOCATE (PGZ0_1)
  DEALLOCATE (PTS_1)
  DEALLOCATE (PQS_1)
  DEALLOCATE (PQICE_1)
  DEALLOCATE (PQLI_1)
  DEALLOCATE (PECT_1)
  DEALLOCATE (PPRODTH_1)
  DEALLOCATE (PNLAB_1)
  DEALLOCATE (PNLABCVP_1)
  DEALLOCATE (PKTROV_1)
  DEALLOCATE (PKUROV_1)
  DEALLOCATE (PXTROV_1)
  DEALLOCATE (PXUROV_1)
  DEALLOCATE (PNBVNO_1)
  DEALLOCATE (PNEBS_1)
  DEALLOCATE (PQCS_1)
  DEALLOCATE (PNEBS0_1)
  DEALLOCATE (PQCS0_1)
  DEALLOCATE (PCOEFN_1)
  DEALLOCATE (PFECT_1)
  DEALLOCATE (PECT1_1)
  DEALLOCATE (PTPRDY_1)
  DEALLOCATE (PEDR_1)
ENDDO
!endif
END PROGRAM MAIN_SIMPLE4_ACTKE
