INTERFACE
#ifdef GPU
ATTRIBUTES (GLOBAL) &
#endif
SUBROUTINE RUN_ACTKE(NGPBLKS, KLON, KLEV, KSIZE, PSTACK)
IMPLICIT NONE
INTEGER(KIND=4), INTENT (   IN) :: NGPBLKS
INTEGER(KIND=4), INTENT (   IN) :: KLON
INTEGER(KIND=4), INTENT (   IN) :: KLEV
INTEGER(KIND=4), INTENT (   IN) :: KSIZE
REAL(KIND=8)   , INTENT (INOUT) :: PSTACK   (KSIZE, NGPBLKS)
END SUBROUTINE RUN_ACTKE
END INTERFACE
