#ifdef GPU
ATTRIBUTES (GLOBAL) &
#endif
SUBROUTINE RUN_ACTKE(NGPBLKS, KLON, KLEV, KSIZE, PSTACK)
IMPLICIT NONE
INTEGER(KIND=4), INTENT (   IN) :: NGPBLKS
INTEGER(KIND=4), INTENT (   IN) :: KLON
INTEGER(KIND=4), INTENT (   IN) :: KLEV
INTEGER(KIND=4), INTENT (   IN) :: KSIZE
REAL(KIND=8)   , INTENT (INOUT) :: PSTACK   (KSIZE, NGPBLKS)

#include "actke.intfb.h"

INTEGER :: IBLOCK, IIDIA, IFDIA


#ifdef GPU
  IBLOCK = BLOCKIDX%X
  IIDIA  = THREADIDX%X
  IFDIA  = THREADIDX%X
#else
!$OMP PARALLEL DO PRIVATE (IBLOCK)
DO IBLOCK = 1, NGPBLKS
  IIDIA = 1
  IFDIA = KLON
#endif

  CALL ACTKE (KLON, KLEV, IIDIA, IFDIA, KSIZE, PSTACK (:, IBLOCK))

#ifdef GPU
#else
ENDDO
!$OMP END PARALLEL DO
#endif

END SUBROUTINE RUN_ACTKE
