#ifdef GPU
ATTRIBUTES (GLOBAL) &
#endif
SUBROUTINE RUN_SIMPLE4_ACTKE(KPROMA, KGPTOT, KTDIAT, KTDIAN, KLEV, PAPHI, &
& PAPHIF, PAPRS, PAPRSF, PDELP, PR, PT, PU, PV, PQ, PLSCPE, PCD, PCH, PGZ0, PTS,      &
& PQS, PQICE, PQLI, PECT, PPRODTH, PNLAB, PNLABCVP, PKTROV, PKUROV, PXTROV,           &
& PXUROV, PNBVNO, PNEBS, PQCS, PNEBS0, PQCS0, PCOEFN, PFECT, PECT1, PTPRDY, PEDR,     &
& RG, RPRTH, ECTMIN, TSPHY, ACBRPHIM, ADISE, ADISI, AKN, ALD, ALMAV, ALMAVE,          &
& ALMAVX, ALPHAE, ALPHAT, ARSB2, ARSC1, ECTMAX, EDB, EDC, EDD, RALPD, RALPS,          &
& RALPW, RATM, RBETD, RBETS, RBETW, RCPV, RCS, RCW, RD, RDT, RETV, RGAMD, RGAMS,      &
& RGAMW, RKAPPA, RLSTT, RLVTT, RTT, RV, UDECT, UPRETMAX, UPRETMIN, USHEARM,           &
& USURIC, VKARMN, KSIZST, KPTRST, PSTACK)
USE PARKIND1, ONLY : JPIM, JPRB
#ifdef CPU
USE OMP_LIB
#endif
IMPLICIT NONE
INTEGER(KIND=JPIM), INTENT (   IN) :: KPROMA
INTEGER(KIND=JPIM), INTENT (   IN) :: KGPTOT     
INTEGER(KIND=JPIM), INTENT (   IN) :: KTDIAT   
INTEGER(KIND=JPIM), INTENT (   IN) :: KTDIAN   
INTEGER(KIND=JPIM), INTENT (   IN) :: KLEV     
REAL(KIND=JPRB)   , INTENT (   IN) :: PAPHI    (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PAPHIF   (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PAPRS    (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PAPRSF   (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PDELP    (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PR       (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PT       (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PU       (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PV       (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PQ       (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PLSCPE   (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PCD      (KGPTOT)
REAL(KIND=JPRB)   , INTENT (   IN) :: PCH      (KGPTOT)
REAL(KIND=JPRB)   , INTENT (   IN) :: PGZ0     (KGPTOT)
REAL(KIND=JPRB)   , INTENT (   IN) :: PTS      (KGPTOT)
REAL(KIND=JPRB)   , INTENT (   IN) :: PQS      (KGPTOT)
REAL(KIND=JPRB)   , INTENT (INOUT) :: PQICE    (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (INOUT) :: PQLI     (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (INOUT) :: PECT     (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PPRODTH  (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PNLAB    (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: PNLABCVP (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PKTROV   (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PKUROV   (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PXTROV   (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PXUROV   (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PNBVNO   (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PNEBS    (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PQCS     (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PNEBS0   (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PQCS0    (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PCOEFN   (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PFECT    (KGPTOT, 0:KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PECT1    (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PTPRDY   (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (  OUT) :: PEDR     (KGPTOT, KLEV)
REAL(KIND=JPRB)   , INTENT (   IN) :: RG       
REAL(KIND=JPRB)   , INTENT (   IN) :: RPRTH    
REAL(KIND=JPRB)   , INTENT (   IN) :: ECTMIN   
REAL(KIND=JPRB)   , INTENT (   IN) :: TSPHY    
REAL(KIND=JPRB)   , INTENT (   IN) :: ACBRPHIM 
REAL(KIND=JPRB)   , INTENT (   IN) :: ADISE    
REAL(KIND=JPRB)   , INTENT (   IN) :: ADISI    
REAL(KIND=JPRB)   , INTENT (   IN) :: AKN      
REAL(KIND=JPRB)   , INTENT (   IN) :: ALD      
REAL(KIND=JPRB)   , INTENT (   IN) :: ALMAV    
REAL(KIND=JPRB)   , INTENT (   IN) :: ALMAVE   
REAL(KIND=JPRB)   , INTENT (   IN) :: ALMAVX   
REAL(KIND=JPRB)   , INTENT (   IN) :: ALPHAE   
REAL(KIND=JPRB)   , INTENT (   IN) :: ALPHAT   
REAL(KIND=JPRB)   , INTENT (   IN) :: ARSB2    
REAL(KIND=JPRB)   , INTENT (   IN) :: ARSC1    
REAL(KIND=JPRB)   , INTENT (   IN) :: ECTMAX   
REAL(KIND=JPRB)   , INTENT (   IN) :: EDB      
REAL(KIND=JPRB)   , INTENT (   IN) :: EDC      
REAL(KIND=JPRB)   , INTENT (   IN) :: EDD      
REAL(KIND=JPRB)   , INTENT (   IN) :: RALPD    
REAL(KIND=JPRB)   , INTENT (   IN) :: RALPS    
REAL(KIND=JPRB)   , INTENT (   IN) :: RALPW    
REAL(KIND=JPRB)   , INTENT (   IN) :: RATM     
REAL(KIND=JPRB)   , INTENT (   IN) :: RBETD    
REAL(KIND=JPRB)   , INTENT (   IN) :: RBETS    
REAL(KIND=JPRB)   , INTENT (   IN) :: RBETW    
REAL(KIND=JPRB)   , INTENT (   IN) :: RCPV     
REAL(KIND=JPRB)   , INTENT (   IN) :: RCS      
REAL(KIND=JPRB)   , INTENT (   IN) :: RCW      
REAL(KIND=JPRB)   , INTENT (   IN) :: RD       
REAL(KIND=JPRB)   , INTENT (   IN) :: RDT      
REAL(KIND=JPRB)   , INTENT (   IN) :: RETV     
REAL(KIND=JPRB)   , INTENT (   IN) :: RGAMD    
REAL(KIND=JPRB)   , INTENT (   IN) :: RGAMS    
REAL(KIND=JPRB)   , INTENT (   IN) :: RGAMW    
REAL(KIND=JPRB)   , INTENT (   IN) :: RKAPPA   
REAL(KIND=JPRB)   , INTENT (   IN) :: RLSTT    
REAL(KIND=JPRB)   , INTENT (   IN) :: RLVTT    
REAL(KIND=JPRB)   , INTENT (   IN) :: RTT      
REAL(KIND=JPRB)   , INTENT (   IN) :: RV       
REAL(KIND=JPRB)   , INTENT (   IN) :: UDECT    
REAL(KIND=JPRB)   , INTENT (   IN) :: UPRETMAX 
REAL(KIND=JPRB)   , INTENT (   IN) :: UPRETMIN 
REAL(KIND=JPRB)   , INTENT (   IN) :: USHEARM  
REAL(KIND=JPRB)   , INTENT (   IN) :: USURIC   
REAL(KIND=JPRB)   , INTENT (   IN) :: VKARMN   
INTEGER(KIND=JPIM), INTENT (   IN) :: KSIZST   
INTEGER(KIND=JPIM), INTENT (   IN) :: KPTRST   
REAL(KIND=JPRB)   , INTENT (INOUT) :: PSTACK   (KGPTOT, KSIZST)

#include "simple4_actke.intfb.h"

INTEGER :: JGLO, IIDIA, IFDIA


#ifdef GPU
  IIDIA = (BLOCKIDX%X-1) * KPROMA + THREADIDX%X
  IFDIA = (BLOCKIDX%X-1) * KPROMA + THREADIDX%X
#else

!$OMP PARALLEL DO PRIVATE (JGLO, IIDIA, IFDIA)
DO JGLO = 1, KGPTOT, KPROMA
  IIDIA = JGLO
  IFDIA = MIN (JGLO + KPROMA - 1, KGPTOT)

#endif

! PRINT *, OMP_GET_THREAD_NUM (), " ", IIDIA, " ", IFDIA

  CALL SIMPLE4_ACTKE (IIDIA, IFDIA, KGPTOT, KTDIAT, KTDIAN, KLEV, PAPHI, PAPHIF,  &
  & PAPRS, PAPRSF,  PDELP, PR, PT, PU, PV, PQ, PLSCPE, PCD, PCH, PGZ0, PTS, PQS,  &
  & PQICE, PQLI, PECT, PPRODTH, PNLAB, PNLABCVP, PKTROV, PKUROV, PXTROV, PXUROV,  &
  & PNBVNO, PNEBS, PQCS, PNEBS0, PQCS0, PCOEFN, PFECT, PECT1, PTPRDY, PEDR, RG,   &
  & RPRTH, ECTMIN, TSPHY, ACBRPHIM, ADISE, ADISI, AKN, ALD, ALMAV, ALMAVE,        &
  & ALMAVX, ALPHAE, ALPHAT, ARSB2, ARSC1, ECTMAX, EDB, EDC, EDD, RALPD, RALPS,    &
  & RALPW, RATM, RBETD, RBETS, RBETW, RCPV, RCS, RCW, RD, RDT, RETV, RGAMD,       &
  & RGAMS, RGAMW, RKAPPA, RLSTT, RLVTT, RTT, RV, UDECT, UPRETMAX, UPRETMIN,       &
  & USHEARM, USURIC, VKARMN, KSIZST, KPTRST, PSTACK)


#ifdef GPU
#else
ENDDO
!$OMP END PARALLEL DO
#endif


END SUBROUTINE RUN_SIMPLE4_ACTKE
