INTERFACE
SUBROUTINE SIMPLE2_ACBL89 ( KIDIA, KFDIA, KLON, KTDIAN, KLEV, PAPHI,&
 & PAPHIF, PAPRS, PAPRSF, PT, PECT, PQV, PQICE, PQLI, PNLAB, PNLABCVP ,&
 & PGZ0, PTS, PUSLE, PLMECT, PPHI3, RG, RETV, RKAPPA, RATM, ALMAVX, ACBRPHIM,&
 & VKARMN, ALD, ECTMIN, ALMAVE, ARSC1) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIAN
REAL(KIND=JPRB) ,INTENT(IN) :: PNLAB(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNLABCVP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PECT(KIDIA:KFDIA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQICE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUSLE(KIDIA:KFDIA,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLMECT(KIDIA:KFDIA,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPHI3(KIDIA:KFDIA,KLEV)
REAL(KIND=JPRB), INTENT ( IN) :: RG
REAL(KIND=JPRB), INTENT ( IN) :: RETV
REAL(KIND=JPRB), INTENT ( IN) :: RKAPPA
REAL(KIND=JPRB), INTENT ( IN) :: RATM
REAL(KIND=JPRB), INTENT ( IN) :: ALMAVX
REAL(KIND=JPRB), INTENT ( IN) :: ACBRPHIM
REAL(KIND=JPRB), INTENT ( IN) :: VKARMN
REAL(KIND=JPRB), INTENT ( IN) :: ALD
REAL(KIND=JPRB), INTENT ( IN) :: ECTMIN
REAL(KIND=JPRB), INTENT ( IN) :: ALMAVE
REAL(KIND=JPRB), INTENT ( IN) :: ARSC1
END SUBROUTINE SIMPLE2_ACBL89
END INTERFACE
