PROGRAM WRAP_ACTKE

#ifdef GPU
#define ATTR_ARG , DEVICE
USE CUDAFOR
#else
#define ATTR_ARG
#endif

USE YOMLOG
USE LOAD_MOD
USE XRD_GETOPTIONS


IMPLICIT NONE


INTERFACE SETALL
  PROCEDURE SETALLI1
  PROCEDURE SETALLI2
  PROCEDURE SETALLX1
  PROCEDURE SETALLX2
END INTERFACE

INTERFACE DDIFF
  PROCEDURE DDIFFX1
  PROCEDURE DDIFFX2
END INTERFACE

INTEGER(KIND=JPIM)          :: KIDIA      
INTEGER(KIND=JPIM)          :: KFDIA      
INTEGER(KIND=JPIM)          :: KLON       
INTEGER(KIND=JPIM)          :: KTDIAT     
INTEGER(KIND=JPIM)          :: KTDIAN     
INTEGER(KIND=JPIM)          :: KLEV       
REAL(KIND=JPRB)             :: RG         
REAL(KIND=JPRB)             :: RPRTH      
REAL(KIND=JPRB)             :: ECTMIN     
REAL(KIND=JPRB)             :: TSPHY      
REAL(KIND=JPRB)             :: ACBRPHIM   
REAL(KIND=JPRB)             :: ADISE      
REAL(KIND=JPRB)             :: ADISI      
REAL(KIND=JPRB)             :: AKN        
REAL(KIND=JPRB)             :: ALD        
REAL(KIND=JPRB)             :: ALMAV      
REAL(KIND=JPRB)             :: ALMAVE     
REAL(KIND=JPRB)             :: ALMAVX     
REAL(KIND=JPRB)             :: ALPHAE     
REAL(KIND=JPRB)             :: ALPHAT     
REAL(KIND=JPRB)             :: ARSB2      
REAL(KIND=JPRB)             :: ARSC1      
REAL(KIND=JPRB)             :: ECTMAX     
REAL(KIND=JPRB)             :: EDB        
REAL(KIND=JPRB)             :: EDC        
REAL(KIND=JPRB)             :: EDD        
REAL(KIND=JPRB)             :: RALPD      
REAL(KIND=JPRB)             :: RALPS      
REAL(KIND=JPRB)             :: RALPW      
REAL(KIND=JPRB)             :: RATM       
REAL(KIND=JPRB)             :: RBETD      
REAL(KIND=JPRB)             :: RBETS      
REAL(KIND=JPRB)             :: RBETW      
REAL(KIND=JPRB)             :: RCPV       
REAL(KIND=JPRB)             :: RCS        
REAL(KIND=JPRB)             :: RCW        
REAL(KIND=JPRB)             :: RD         
REAL(KIND=JPRB)             :: RDT        
REAL(KIND=JPRB)             :: RETV       
REAL(KIND=JPRB)             :: RGAMD      
REAL(KIND=JPRB)             :: RGAMS      
REAL(KIND=JPRB)             :: RGAMW      
REAL(KIND=JPRB)             :: RKAPPA     
REAL(KIND=JPRB)             :: RLSTT      
REAL(KIND=JPRB)             :: RLVTT      
REAL(KIND=JPRB)             :: RTT        
REAL(KIND=JPRB)             :: RV         
REAL(KIND=JPRB)             :: UDECT      
REAL(KIND=JPRB)             :: UPRETMAX   
REAL(KIND=JPRB)             :: UPRETMIN   
REAL(KIND=JPRB)             :: USHEARM    
REAL(KIND=JPRB)             :: USURIC     
REAL(KIND=JPRB)             :: VKARMN     
INTEGER(KIND=JPIM)          :: KSIZST     
INTEGER(KIND=JPIM)          :: KPTRST     
REAL(KIND=JPRB)   , POINTER :: PSTACK     (:, :)
INTEGER(KIND=JPIM)          :: ICOUNT    
INTEGER(KIND=JPIM)          :: IDUM
REAL(KIND=JPRB)             :: ZDUM
INTEGER(KIND=JPIM) ATTR_ARG :: KPROMA_DEV    
INTEGER(KIND=JPIM) ATTR_ARG :: KIDIA_DEV    
INTEGER(KIND=JPIM) ATTR_ARG :: KFDIA_DEV    
INTEGER(KIND=JPIM) ATTR_ARG :: NGPTOT_DEV     
INTEGER(KIND=JPIM) ATTR_ARG :: KTDIAT_DEV   
INTEGER(KIND=JPIM) ATTR_ARG :: KTDIAN_DEV   
INTEGER(KIND=JPIM) ATTR_ARG :: KLEV_DEV     
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPHI_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPHIF_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPRS_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPRSF_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PDELP_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PR_DEV       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PT_DEV       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PU_DEV       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PV_DEV       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQ_DEV       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PLSCPE_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCD_DEV      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCH_DEV      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PGZ0_DEV     (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PTS_DEV      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQS_DEV      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQICE_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQLI_DEV     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PECT_DEV     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PPRODTH_DEV  (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNLAB_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNLABCVP_DEV (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PKTROV_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PKUROV_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PXTROV_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PXUROV_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNBVNO_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNEBS_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQCS_DEV     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNEBS0_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQCS0_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCOEFN_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PFECT_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PECT1_DEV    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PTPRDY_DEV   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PEDR_DEV     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG          :: RG_DEV       
REAL(KIND=JPRB) ATTR_ARG          :: RPRTH_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: ECTMIN_DEV   
REAL(KIND=JPRB) ATTR_ARG          :: TSPHY_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: ACBRPHIM_DEV 
REAL(KIND=JPRB) ATTR_ARG          :: ADISE_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: ADISI_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: AKN_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: ALD_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: ALMAV_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: ALMAVE_DEV   
REAL(KIND=JPRB) ATTR_ARG          :: ALMAVX_DEV   
REAL(KIND=JPRB) ATTR_ARG          :: ALPHAE_DEV   
REAL(KIND=JPRB) ATTR_ARG          :: ALPHAT_DEV   
REAL(KIND=JPRB) ATTR_ARG          :: ARSB2_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: ARSC1_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: ECTMAX_DEV   
REAL(KIND=JPRB) ATTR_ARG          :: EDB_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: EDC_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: EDD_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: RALPD_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RALPS_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RALPW_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RATM_DEV     
REAL(KIND=JPRB) ATTR_ARG          :: RBETD_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RBETS_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RBETW_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RCPV_DEV     
REAL(KIND=JPRB) ATTR_ARG          :: RCS_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: RCW_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: RD_DEV       
REAL(KIND=JPRB) ATTR_ARG          :: RDT_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: RETV_DEV     
REAL(KIND=JPRB) ATTR_ARG          :: RGAMD_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RGAMS_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RGAMW_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RKAPPA_DEV   
REAL(KIND=JPRB) ATTR_ARG          :: RLSTT_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RLVTT_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: RTT_DEV      
REAL(KIND=JPRB) ATTR_ARG          :: RV_DEV       
REAL(KIND=JPRB) ATTR_ARG          :: UDECT_DEV    
REAL(KIND=JPRB) ATTR_ARG          :: UPRETMAX_DEV 
REAL(KIND=JPRB) ATTR_ARG          :: UPRETMIN_DEV 
REAL(KIND=JPRB) ATTR_ARG          :: USHEARM_DEV  
REAL(KIND=JPRB) ATTR_ARG          :: USURIC_DEV   
REAL(KIND=JPRB) ATTR_ARG          :: VKARMN_DEV   
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PSTACK_DEV (:, :, :)
INTEGER(KIND=JPIM) ATTR_ARG       :: KSIZST_DEV
INTEGER(KIND=JPIM) ATTR_ARG       :: KPTRST_DEV
INTEGER(KIND=JPIM) ATTR_ARG       :: ICOUNT_DEV
INTEGER, ALLOCATABLE :: IFDIA (:)
INTEGER :: IBL
INTEGER :: ISTAT, II
INTEGER :: ICOUNT1, KLON1
INTEGER :: ICOUNT0, KLON0, NPROMA
LOGICAL :: LLDIFF, LLPRINT
CHARACTER (LEN=32) :: CLCASE

INTEGER :: IFILE, ILINE, IIND
REAL :: ZVALUE
INTEGER :: NTIMES 
INTEGER :: JLON1DIFF, JLON2DIFF, JLONSDIFF

#ifdef GPU
TYPE (CUDAEVENT) :: STARTEVENT, STOPEVENT
#endif
REAL :: TIME
INTEGER :: ZV1 (8), ZV0 (8), IC

#include "run_simple4_actke.intfb.h"

CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
NPROMA = 32
CALL GETOPTION ("--nproma", NPROMA)
JLON1DIFF = -1; CALL GETOPTION ("--jlon1diff", JLON1DIFF)
JLON2DIFF = -1; CALL GETOPTION ("--jlon2diff", JLON2DIFF)
JLONSDIFF =  1; CALL GETOPTION ("--jlonsdiff", JLONSDIFF)
NTIMES    = 10; CALL GETOPTION ("--times",     NTIMES   )
CALL CHECKOPTIONS ()


ICOUNT1 = 0 
KLON1 = 0 

OPEN (ILUNC, FILE=TRIM (CLCASE)//"/ACTKE.COUNT", FORM="FORMATTED")
READ (ILUNC, *) ICOUNT
CLOSE (ILUNC)

IF (ICOUNT /= 1) STOP

IF (ICOUNT1 == 0) ICOUNT1 = ICOUNT

ALLOCATE (IFDIA (ICOUNT))

PRINT *, "-- READ"

CALL OPEN_LOAD (TRIM (CLCASE)//"/ACTKE")
DO IBL = 1, ICOUNT

  PRINT *, IBL

  CALL LOAD (ILUN_IN, KIDIA)
  CALL LOAD (ILUN_IN, IFDIA (IBL))
  CALL LOAD (ILUN_IN, KLON)
  IF (IBL == 1) THEN
    PRINT *, " KLON = ", KLON
    IF (JLON1DIFF < 0) JLON1DIFF = 1
    IF (JLON2DIFF < 0) JLON2DIFF = KLON
    IF (JLON2DIFF > KLON) JLON2DIFF = KLON
  ENDIF
  IF (KLON1 == 0) KLON1 = KLON
  CALL LOAD (ILUN_IN, KTDIAT)
  CALL LOAD (ILUN_IN, KTDIAN)
  CALL LOAD (ILUN_IN, KLEV)
#define SET(x) CALL SETALL (x##_DEV)
  PRINT *, " PAPHI    "; SET (PAPHI)
  PRINT *, " PAPHIF   "; SET (PAPHIF)
  PRINT *, " PAPRS    "; SET (PAPRS)
  PRINT *, " PAPRSF   "; SET (PAPRSF) 
  PRINT *, " PDELP    "; SET (PDELP)
  PRINT *, " PR       "; SET (PR)
  PRINT *, " PT       "; SET (PT)
  PRINT *, " PU       "; SET (PU)
  PRINT *, " PV       "; SET (PV)
  PRINT *, " PQ       "; SET (PQ) 
  PRINT *, " PLSCPE   "; SET (PLSCPE)
  PRINT *, " PCD      "; SET (PCD)
  PRINT *, " PCH      "; SET (PCH)
  PRINT *, " PGZ0     "; SET (PGZ0)
  PRINT *, " PTS      "; SET (PTS)
  PRINT *, " PQS      "; SET (PQS)
  PRINT *, " PQICE    "; SET (PQICE)
  PRINT *, " PQLI     "; SET (PQLI)
  PRINT *, " PECT     "; SET (PECT) 
  PRINT *, " PPRODTH  "; SET (PPRODTH)
  PRINT *, " PNLAB    "; SET (PNLAB)
  PRINT *, " PNLABCVP "; SET (PNLABCVP)
  PRINT *, " PKTROV   "; SET (PKTROV)
  PRINT *, " PKUROV   "; SET (PKUROV)
  PRINT *, " PXTROV   "; SET (PXTROV)
  PRINT *, " PXUROV   "; SET (PXUROV)
  PRINT *, " PNBVNO   "; SET (PNBVNO)
  PRINT *, " PNEBS    "; SET (PNEBS)
  PRINT *, " PQCS     "; SET (PQCS)
  PRINT *, " PNEBS0   "; SET (PNEBS0)
  PRINT *, " PQCS0    "; SET (PQCS0)
  PRINT *, " PCOEFN   "; SET (PCOEFN)
  PRINT *, " PFECT    "; SET (PFECT)
  PRINT *, " PECT1    "; SET (PECT1)
  PRINT *, " PTPRDY   "; SET (PTPRDY)
  PRINT *, " PEDR     "; SET (PEDR)
  CALL LOAD (ILUN_IN, RG)
  CALL LOAD (ILUN_IN, RPRTH)
  CALL LOAD (ILUN_IN, ECTMIN)
  CALL LOAD (ILUN_IN, TSPHY)
  CALL LOAD (ILUN_IN, ACBRPHIM)
  CALL LOAD (ILUN_IN, ADISE)
  CALL LOAD (ILUN_IN, ADISI)
  CALL LOAD (ILUN_IN, AKN)
  CALL LOAD (ILUN_IN, ALD)
  CALL LOAD (ILUN_IN, ALMAV)
  CALL LOAD (ILUN_IN, ALMAVE)
  CALL LOAD (ILUN_IN, ALMAVX)
  CALL LOAD (ILUN_IN, ALPHAE)
  CALL LOAD (ILUN_IN, ALPHAT)
  CALL LOAD (ILUN_IN, ARSB2)
  CALL LOAD (ILUN_IN, ARSC1)
  CALL LOAD (ILUN_IN, ECTMAX)
  CALL LOAD (ILUN_IN, EDB)
  CALL LOAD (ILUN_IN, EDC)
  CALL LOAD (ILUN_IN, EDD)
  CALL LOAD (ILUN_IN, RALPD)
  CALL LOAD (ILUN_IN, RALPS)
  CALL LOAD (ILUN_IN, RALPW)
  CALL LOAD (ILUN_IN, RATM)
  CALL LOAD (ILUN_IN, RBETD)
  CALL LOAD (ILUN_IN, RBETS)
  CALL LOAD (ILUN_IN, RBETW)
  CALL LOAD (ILUN_IN, RCPV)
  CALL LOAD (ILUN_IN, RCS)
  CALL LOAD (ILUN_IN, RCW)
  CALL LOAD (ILUN_IN, RD)
  CALL LOAD (ILUN_IN, RDT)
  CALL LOAD (ILUN_IN, RETV)
  CALL LOAD (ILUN_IN, RGAMD)
  CALL LOAD (ILUN_IN, RGAMS)
  CALL LOAD (ILUN_IN, RGAMW)
  CALL LOAD (ILUN_IN, RKAPPA)
  CALL LOAD (ILUN_IN, RLSTT)
  CALL LOAD (ILUN_IN, RLVTT)
  CALL LOAD (ILUN_IN, RTT)
  CALL LOAD (ILUN_IN, RV)
  CALL LOAD (ILUN_IN, UDECT)
  CALL LOAD (ILUN_IN, UPRETMAX)
  CALL LOAD (ILUN_IN, UPRETMIN)
  CALL LOAD (ILUN_IN, USHEARM)
  CALL LOAD (ILUN_IN, USURIC)
  CALL LOAD (ILUN_IN, VKARMN)
ENDDO

KLON0 = KLON; ICOUNT0 = ICOUNT
KLON = KLON1; ICOUNT = ICOUNT1

KSIZST = 21 * KLEV + 10
KPTRST = 1
ALLOCATE (PSTACK_DEV (KLON, KSIZST, ICOUNT))

KPROMA_DEV = NPROMA

KIDIA = 1
KFDIA = KLON

KIDIA_DEV = KIDIA
KFDIA_DEV = KFDIA
NGPTOT_DEV = KLON
KTDIAT_DEV = KTDIAT
KTDIAN_DEV = KTDIAN
KLEV_DEV = KLEV
RG_DEV = RG
RPRTH_DEV = RPRTH
ECTMIN_DEV = ECTMIN
TSPHY_DEV = TSPHY
ACBRPHIM_DEV = ACBRPHIM
ADISE_DEV = ADISE
ADISI_DEV = ADISI
AKN_DEV = AKN
ALD_DEV = ALD
ALMAV_DEV = ALMAV
ALMAVE_DEV = ALMAVE
ALMAVX_DEV = ALMAVX
ALPHAE_DEV = ALPHAE
ALPHAT_DEV = ALPHAT
ARSB2_DEV = ARSB2
ARSC1_DEV = ARSC1
ECTMAX_DEV = ECTMAX
EDB_DEV = EDB
EDC_DEV = EDC
EDD_DEV = EDD
RALPD_DEV = RALPD
RALPS_DEV = RALPS
RALPW_DEV = RALPW
RATM_DEV = RATM
RBETD_DEV = RBETD
RBETS_DEV = RBETS
RBETW_DEV = RBETW
RCPV_DEV = RCPV
RCS_DEV = RCS
RCW_DEV = RCW
RD_DEV = RD
RDT_DEV = RDT
RETV_DEV = RETV
RGAMD_DEV = RGAMD
RGAMS_DEV = RGAMS
RGAMW_DEV = RGAMW
RKAPPA_DEV = RKAPPA
RLSTT_DEV = RLSTT
RLVTT_DEV = RLVTT
RTT_DEV = RTT
RV_DEV = RV
UDECT_DEV = UDECT
UPRETMAX_DEV = UPRETMAX
UPRETMIN_DEV = UPRETMIN
USHEARM_DEV = USHEARM
USURIC_DEV = USURIC
VKARMN_DEV = VKARMN
KSIZST_DEV = KSIZST
KPTRST_DEV = KPTRST
ICOUNT_DEV = ICOUNT


CALL DATE_AND_TIME (VALUES=ZV0)

PRINT *, "-- RUN"

#ifdef GPU
ISTAT = CUDAEVENTCREATE (STARTEVENT)
ISTAT = CUDAEVENTCREATE (STOPEVENT)
ISTAT = CUDAEVENTRECORD (STARTEVENT, 0)
#endif

#ifdef GPU
PRINT *, " BLOCK GPU = ", KLON/NPROMA, " NPROMA = ", NPROMA
#endif

DO IC = 1, NTIMES

#ifdef GPU
CALL RUN_SIMPLE4_ACTKE <<<KLON/NPROMA, NPROMA>>> &
#else
CALL RUN_SIMPLE4_ACTKE &
#endif
&                                     (KPROMA_DEV, NGPTOT_DEV, KTDIAT_DEV, KTDIAN_DEV, KLEV_DEV,    &
& PAPHI_DEV, PAPHIF_DEV, PAPRS_DEV, PAPRSF_DEV, PDELP_DEV, PR_DEV, PT_DEV, PU_DEV, PV_DEV, PQ_DEV,  &
& PLSCPE_DEV, PCD_DEV, PCH_DEV, PGZ0_DEV, PTS_DEV, PQS_DEV, PQICE_DEV, PQLI_DEV, PECT_DEV,          &
& PPRODTH_DEV, PNLAB_DEV, PNLABCVP_DEV, PKTROV_DEV, PKUROV_DEV, PXTROV_DEV, PXUROV_DEV, PNBVNO_DEV, &
& PNEBS_DEV, PQCS_DEV, PNEBS0_DEV, PQCS0_DEV, PCOEFN_DEV, PFECT_DEV, PECT1_DEV, PTPRDY_DEV,         &
& PEDR_DEV, RG_DEV, RPRTH_DEV, ECTMIN_DEV, TSPHY_DEV, ACBRPHIM_DEV, ADISE_DEV, ADISI_DEV, AKN_DEV,  &
& ALD_DEV, ALMAV_DEV, ALMAVE_DEV, ALMAVX_DEV, ALPHAE_DEV, ALPHAT_DEV, ARSB2_DEV, ARSC1_DEV,         &
& ECTMAX_DEV, EDB_DEV, EDC_DEV, EDD_DEV, RALPD_DEV, RALPS_DEV, RALPW_DEV, RATM_DEV, RBETD_DEV,      &
& RBETS_DEV, RBETW_DEV, RCPV_DEV, RCS_DEV, RCW_DEV, RD_DEV, RDT_DEV, RETV_DEV, RGAMD_DEV,           &
& RGAMS_DEV, RGAMW_DEV, RKAPPA_DEV, RLSTT_DEV, RLVTT_DEV, RTT_DEV, RV_DEV, UDECT_DEV, UPRETMAX_DEV, &
& UPRETMIN_DEV, USHEARM_DEV, USURIC_DEV, VKARMN_DEV, KSIZST_DEV, KPTRST_DEV, PSTACK_DEV)


#ifdef GPU
ISTAT = CUDAGETLASTERROR ()
IF (ISTAT /= CUDASUCCESS) PRINT *, CUDAGETERRORSTRING (ISTAT)
#endif


ENDDO

#ifdef GPU
ISTAT = CUDADEVICESYNCHRONIZE ()
ISTAT = CUDAEVENTRECORD (STOPEVENT, 0)
ISTAT = CUDAEVENTSYNCHRONIZE (STOPEVENT)
ISTAT = CUDAEVENTELAPSEDTIME (TIME, STARTEVENT, STOPEVENT)

PRINT *, " CUDAEVENTELAPSEDTIME = ", TIME / NTIMES, " milliseconds"

#else

PRINT *

#endif

#ifdef GPU
ISTAT = CUDADEVICESYNCHRONIZE ()
#endif

CALL DATE_AND_TIME (VALUES=ZV1)

PRINT *, " DATE_AND_TIME = ", (REAL (ZV1 (5) - ZV0 (5), 8) * 3600._8 + REAL (ZV1 (6) - ZV0 (6), 8) * 60._8 + & 
& REAL (ZV1 (7) - ZV0 (7), 8) + REAL (ZV1 (8) - ZV0 (8), 8) / 1000._8) / NTIMES, " seconds"


#ifdef UNDEF
WRITE (0, *) __FILE__, ':', __LINE__ 

DO II = 1, 2000
  IFILE = NFILE  (II)
  IF (IFILE == 0) EXIT
  ILINE  = NLINE  (II)
  IIND   = NIND   (II)
  ZVALUE = RVALUE (II)
  WRITE (*, '(A,":",I0," ",I6," ",E20.12)') CHAR (IFILE), ILINE, IIND, ZVALUE
ENDDO
#endif


IF (LLDIFF .AND. ICOUNT0 == ICOUNT1 .AND. KLON0 == KLON1) THEN

PRINT *, "-- DIFF"

DO IBL = 1, ICOUNT

  LLPRINT = .TRUE.

  IF (LLPRINT) WRITE (*, *) "---", IBL

#define DIFFD(x) CALL DDIFF (#x, x##_DEV, LLPRINT)

  CALL LOAD (ILUN_OUT, IDUM); CALL LOAD (ILUN_OUT, IDUM); CALL LOAD (ILUN_OUT, IDUM); CALL LOAD (ILUN_OUT, IDUM);
  CALL LOAD (ILUN_OUT, IDUM); CALL LOAD (ILUN_OUT, IDUM);
  DIFFD (PAPHI)
  DIFFD (PAPHIF)
  DIFFD (PAPRS)
  DIFFD (PAPRSF)
  DIFFD (PDELP) !
  DIFFD (PR)
  DIFFD (PT)
  DIFFD (PU)
  DIFFD (PV)
  DIFFD (PQ)
  DIFFD (PLSCPE)
  DIFFD (PCD)
  DIFFD (PCH)
  DIFFD (PGZ0)
  DIFFD (PTS)
  DIFFD (PQS)
  DIFFD (PQICE)
  DIFFD (PQLI)
  DIFFD (PECT)
  DIFFD (PPRODTH)
  DIFFD (PNLAB)
  DIFFD (PNLABCVP)
  DIFFD (PKTROV)
  DIFFD (PKUROV)
  DIFFD (PXTROV)
  DIFFD (PXUROV)
  DIFFD (PNBVNO)
  DIFFD (PNEBS)
  DIFFD (PQCS)
  DIFFD (PNEBS0)
  DIFFD (PQCS0)
  DIFFD (PCOEFN)
  DIFFD (PFECT)
  DIFFD (PECT1)
  DIFFD (PTPRDY)
  DIFFD (PEDR)
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
ENDDO

ENDIF

CONTAINS

#include "contains.h"

END PROGRAM WRAP_ACTKE
