PROGRAM WRAP_ACTKE

#ifdef GPU
#define ATTR_ARG , DEVICE
USE CUDAFOR
#else
#define ATTR_ARG
#endif

USE YOMLOG
USE LOAD_MOD
USE XRD_GETOPTIONS


IMPLICIT NONE


INTERFACE SETALL
  PROCEDURE SETALLI1
  PROCEDURE SETALLI2
  PROCEDURE SETALLX1
  PROCEDURE SETALLX2
END INTERFACE

INTERFACE DDIFF
  PROCEDURE DDIFFX1
  PROCEDURE DDIFFX2
END INTERFACE

INTEGER(KIND=JPIM)          :: KIDIA      
INTEGER(KIND=JPIM)          :: KFDIA      
INTEGER(KIND=JPIM)          :: KLON       
INTEGER(KIND=JPIM)          :: KTDIAT     
INTEGER(KIND=JPIM)          :: KTDIAN     
INTEGER(KIND=JPIM)          :: KLEV       
REAL(KIND=JPRB)             :: RG         
REAL(KIND=JPRB)             :: RPRTH      
REAL(KIND=JPRB)             :: ECTMIN     
REAL(KIND=JPRB)             :: TSPHY      
REAL(KIND=JPRB)             :: ACBRPHIM   
REAL(KIND=JPRB)             :: ADISE      
REAL(KIND=JPRB)             :: ADISI      
REAL(KIND=JPRB)             :: AKN        
REAL(KIND=JPRB)             :: ALD        
REAL(KIND=JPRB)             :: ALMAV      
REAL(KIND=JPRB)             :: ALMAVE     
REAL(KIND=JPRB)             :: ALMAVX     
REAL(KIND=JPRB)             :: ALPHAE     
REAL(KIND=JPRB)             :: ALPHAT     
REAL(KIND=JPRB)             :: ARSB2      
REAL(KIND=JPRB)             :: ARSC1      
REAL(KIND=JPRB)             :: ECTMAX     
REAL(KIND=JPRB)             :: EDB        
REAL(KIND=JPRB)             :: EDC        
REAL(KIND=JPRB)             :: EDD        
REAL(KIND=JPRB)             :: RALPD      
REAL(KIND=JPRB)             :: RALPS      
REAL(KIND=JPRB)             :: RALPW      
REAL(KIND=JPRB)             :: RATM       
REAL(KIND=JPRB)             :: RBETD      
REAL(KIND=JPRB)             :: RBETS      
REAL(KIND=JPRB)             :: RBETW      
REAL(KIND=JPRB)             :: RCPV       
REAL(KIND=JPRB)             :: RCS        
REAL(KIND=JPRB)             :: RCW        
REAL(KIND=JPRB)             :: RD         
REAL(KIND=JPRB)             :: RDT        
REAL(KIND=JPRB)             :: RETV       
REAL(KIND=JPRB)             :: RGAMD      
REAL(KIND=JPRB)             :: RGAMS      
REAL(KIND=JPRB)             :: RGAMW      
REAL(KIND=JPRB)             :: RKAPPA     
REAL(KIND=JPRB)             :: RLSTT      
REAL(KIND=JPRB)             :: RLVTT      
REAL(KIND=JPRB)             :: RTT        
REAL(KIND=JPRB)             :: RV         
REAL(KIND=JPRB)             :: UDECT      
REAL(KIND=JPRB)             :: UPRETMAX   
REAL(KIND=JPRB)             :: UPRETMIN   
REAL(KIND=JPRB)             :: USHEARM    
REAL(KIND=JPRB)             :: USURIC     
REAL(KIND=JPRB)             :: VKARMN     
INTEGER(KIND=JPIM)          :: KSIZST     
INTEGER(KIND=JPIM)          :: KPTRST     
REAL(KIND=JPRB)   , POINTER :: PSTACK     (:, :)
INTEGER(KIND=JPIM)          :: ICOUNT    
INTEGER(KIND=JPIM)          :: IDUM
REAL(KIND=JPRB)             :: ZDUM
INTEGER(KIND=JPIM) ATTR_ARG :: KIDIA_ALL    
INTEGER(KIND=JPIM) ATTR_ARG :: KFDIA_ALL    
INTEGER(KIND=JPIM) ATTR_ARG :: KLON_ALL     
INTEGER(KIND=JPIM) ATTR_ARG :: KTDIAT_ALL   
INTEGER(KIND=JPIM) ATTR_ARG :: KTDIAN_ALL   
INTEGER(KIND=JPIM) ATTR_ARG :: KLEV_ALL     
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPHI_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPHIF_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPRS_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PAPRSF_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PDELP_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PR_ALL       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PT_ALL       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PU_ALL       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PV_ALL       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQ_ALL       (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PLSCPE_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCD_ALL      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCH_ALL      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PGZ0_ALL     (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PTS_ALL      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQS_ALL      (:, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQICE_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQLI_ALL     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PECT_ALL     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PPRODTH_ALL  (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNLAB_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNLABCVP_ALL (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PKTROV_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PKUROV_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PXTROV_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PXUROV_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNBVNO_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNEBS_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQCS_ALL     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PNEBS0_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PQCS0_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PCOEFN_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PFECT_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PECT1_ALL    (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PTPRDY_ALL   (:, :, :)
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PEDR_ALL     (:, :, :)
REAL(KIND=JPRB) ATTR_ARG          :: RG_ALL       
REAL(KIND=JPRB) ATTR_ARG          :: RPRTH_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: ECTMIN_ALL   
REAL(KIND=JPRB) ATTR_ARG          :: TSPHY_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: ACBRPHIM_ALL 
REAL(KIND=JPRB) ATTR_ARG          :: ADISE_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: ADISI_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: AKN_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: ALD_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: ALMAV_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: ALMAVE_ALL   
REAL(KIND=JPRB) ATTR_ARG          :: ALMAVX_ALL   
REAL(KIND=JPRB) ATTR_ARG          :: ALPHAE_ALL   
REAL(KIND=JPRB) ATTR_ARG          :: ALPHAT_ALL   
REAL(KIND=JPRB) ATTR_ARG          :: ARSB2_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: ARSC1_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: ECTMAX_ALL   
REAL(KIND=JPRB) ATTR_ARG          :: EDB_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: EDC_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: EDD_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: RALPD_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RALPS_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RALPW_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RATM_ALL     
REAL(KIND=JPRB) ATTR_ARG          :: RBETD_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RBETS_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RBETW_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RCPV_ALL     
REAL(KIND=JPRB) ATTR_ARG          :: RCS_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: RCW_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: RD_ALL       
REAL(KIND=JPRB) ATTR_ARG          :: RDT_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: RETV_ALL     
REAL(KIND=JPRB) ATTR_ARG          :: RGAMD_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RGAMS_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RGAMW_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RKAPPA_ALL   
REAL(KIND=JPRB) ATTR_ARG          :: RLSTT_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RLVTT_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: RTT_ALL      
REAL(KIND=JPRB) ATTR_ARG          :: RV_ALL       
REAL(KIND=JPRB) ATTR_ARG          :: UDECT_ALL    
REAL(KIND=JPRB) ATTR_ARG          :: UPRETMAX_ALL 
REAL(KIND=JPRB) ATTR_ARG          :: UPRETMIN_ALL 
REAL(KIND=JPRB) ATTR_ARG          :: USHEARM_ALL  
REAL(KIND=JPRB) ATTR_ARG          :: USURIC_ALL   
REAL(KIND=JPRB) ATTR_ARG          :: VKARMN_ALL   
REAL(KIND=JPRB) ATTR_ARG, POINTER :: PSTACK_ALL (:, :, :)
INTEGER(KIND=JPIM) ATTR_ARG       :: KSIZST_ALL
INTEGER(KIND=JPIM) ATTR_ARG       :: KPTRST_ALL
INTEGER(KIND=JPIM) ATTR_ARG       :: ICOUNT_ALL
INTEGER, ALLOCATABLE :: IFDIA (:)
INTEGER :: IBL
INTEGER :: ISTAT, II
INTEGER :: ICOUNT1, KLON1
INTEGER :: ICOUNT0, KLON0
LOGICAL :: LLDIFF, LLPRINT
CHARACTER (LEN=32) :: CLCASE
INTEGER, POINTER :: IDIFFBLOCK (:) => NULL ()

INTEGER :: IFILE, ILINE, IIND
REAL :: ZVALUE

#ifdef GPU
TYPE (CUDAEVENT) :: STARTEVENT, STOPEVENT
#endif
REAL :: TIME
INTEGER :: ZV1 (8), ZV0 (8), IC

#include "run_simple4_actke.intfb.h"

CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--diff-block-list", IDIFFBLOCK)
ICOUNT1 = 0 
CALL GETOPTION ("--count", ICOUNT1)
KLON1 = 0 
CALL GETOPTION ("--nproma", KLON1)
CALL CHECKOPTIONS ()



ALLOCATE (IPTR (1), NFILE (2000), NLINE (2000), NIND (2000), RVALUE (2000))
IPTR (1) = 0
DO II = 1, 2000
NFILE (II) = 0
NLINE (II) = 0
RVALUE (II) = -999.999
ENDDO

OPEN (ILUNC, FILE=TRIM (CLCASE)//"/ACTKE.COUNT", FORM="FORMATTED")
READ (ILUNC, *) ICOUNT
CLOSE (ILUNC)

IF (ICOUNT1 == 0) ICOUNT1 = ICOUNT

ALLOCATE (IFDIA (ICOUNT))

PRINT *, "-- READ"

CALL OPEN_LOAD (TRIM (CLCASE)//"/ACTKE")
DO IBL = 1, ICOUNT

  PRINT *, IBL

  CALL LOAD (ILUN_IN, KIDIA)
  CALL LOAD (ILUN_IN, IFDIA (IBL))
  CALL LOAD (ILUN_IN, KLON)
  IF (KLON1 == 0) KLON1 = KLON
  CALL LOAD (ILUN_IN, KTDIAT)
  CALL LOAD (ILUN_IN, KTDIAN)
  CALL LOAD (ILUN_IN, KLEV)
#define SET(x) CALL SETALL (x##_ALL)
  SET (PAPHI)
  SET (PAPHIF)
  SET (PAPRS)
  SET (PAPRSF) 
  SET (PDELP)
  SET (PR)
  SET (PT)
  SET (PU)
  SET (PV)
  SET (PQ) 
  SET (PLSCPE)
  SET (PCD)
  SET (PCH)
  SET (PGZ0)
  SET (PTS)
  SET (PQS)
  SET (PQICE)
  SET (PQLI)
  SET (PECT) 
  SET (PPRODTH)
  SET (PNLAB)
  SET (PNLABCVP)
  SET (PKTROV)
  SET (PKUROV)
  SET (PXTROV)
  SET (PXUROV)
  SET (PNBVNO)
  SET (PNEBS)
  SET (PQCS)
  SET (PNEBS0)
  SET (PQCS0)
  SET (PCOEFN)
  SET (PFECT)
  SET (PECT1)
  SET (PTPRDY)
  SET (PEDR)
  CALL LOAD (ILUN_IN, RG)
  CALL LOAD (ILUN_IN, RPRTH)
  CALL LOAD (ILUN_IN, ECTMIN)
  CALL LOAD (ILUN_IN, TSPHY)
  CALL LOAD (ILUN_IN, ACBRPHIM)
  CALL LOAD (ILUN_IN, ADISE)
  CALL LOAD (ILUN_IN, ADISI)
  CALL LOAD (ILUN_IN, AKN)
  CALL LOAD (ILUN_IN, ALD)
  CALL LOAD (ILUN_IN, ALMAV)
  CALL LOAD (ILUN_IN, ALMAVE)
  CALL LOAD (ILUN_IN, ALMAVX)
  CALL LOAD (ILUN_IN, ALPHAE)
  CALL LOAD (ILUN_IN, ALPHAT)
  CALL LOAD (ILUN_IN, ARSB2)
  CALL LOAD (ILUN_IN, ARSC1)
  CALL LOAD (ILUN_IN, ECTMAX)
  CALL LOAD (ILUN_IN, EDB)
  CALL LOAD (ILUN_IN, EDC)
  CALL LOAD (ILUN_IN, EDD)
  CALL LOAD (ILUN_IN, RALPD)
  CALL LOAD (ILUN_IN, RALPS)
  CALL LOAD (ILUN_IN, RALPW)
  CALL LOAD (ILUN_IN, RATM)
  CALL LOAD (ILUN_IN, RBETD)
  CALL LOAD (ILUN_IN, RBETS)
  CALL LOAD (ILUN_IN, RBETW)
  CALL LOAD (ILUN_IN, RCPV)
  CALL LOAD (ILUN_IN, RCS)
  CALL LOAD (ILUN_IN, RCW)
  CALL LOAD (ILUN_IN, RD)
  CALL LOAD (ILUN_IN, RDT)
  CALL LOAD (ILUN_IN, RETV)
  CALL LOAD (ILUN_IN, RGAMD)
  CALL LOAD (ILUN_IN, RGAMS)
  CALL LOAD (ILUN_IN, RGAMW)
  CALL LOAD (ILUN_IN, RKAPPA)
  CALL LOAD (ILUN_IN, RLSTT)
  CALL LOAD (ILUN_IN, RLVTT)
  CALL LOAD (ILUN_IN, RTT)
  CALL LOAD (ILUN_IN, RV)
  CALL LOAD (ILUN_IN, UDECT)
  CALL LOAD (ILUN_IN, UPRETMAX)
  CALL LOAD (ILUN_IN, UPRETMIN)
  CALL LOAD (ILUN_IN, USHEARM)
  CALL LOAD (ILUN_IN, USURIC)
  CALL LOAD (ILUN_IN, VKARMN)
ENDDO

KLON0 = KLON; ICOUNT0 = ICOUNT
KLON = KLON1; ICOUNT = ICOUNT1

KSIZST = 21 * KLEV + 10
KPTRST = 1
ALLOCATE (PSTACK_ALL (KLON, KSIZST, ICOUNT))
KIDIA = 1
KFDIA = KLON
KIDIA_ALL = KIDIA
KFDIA_ALL = KFDIA
KLON_ALL = KLON
KTDIAT_ALL = KTDIAT
KTDIAN_ALL = KTDIAN
KLEV_ALL = KLEV
RG_ALL = RG
RPRTH_ALL = RPRTH
ECTMIN_ALL = ECTMIN
TSPHY_ALL = TSPHY
ACBRPHIM_ALL = ACBRPHIM
ADISE_ALL = ADISE
ADISI_ALL = ADISI
AKN_ALL = AKN
ALD_ALL = ALD
ALMAV_ALL = ALMAV
ALMAVE_ALL = ALMAVE
ALMAVX_ALL = ALMAVX
ALPHAE_ALL = ALPHAE
ALPHAT_ALL = ALPHAT
ARSB2_ALL = ARSB2
ARSC1_ALL = ARSC1
ECTMAX_ALL = ECTMAX
EDB_ALL = EDB
EDC_ALL = EDC
EDD_ALL = EDD
RALPD_ALL = RALPD
RALPS_ALL = RALPS
RALPW_ALL = RALPW
RATM_ALL = RATM
RBETD_ALL = RBETD
RBETS_ALL = RBETS
RBETW_ALL = RBETW
RCPV_ALL = RCPV
RCS_ALL = RCS
RCW_ALL = RCW
RD_ALL = RD
RDT_ALL = RDT
RETV_ALL = RETV
RGAMD_ALL = RGAMD
RGAMS_ALL = RGAMS
RGAMW_ALL = RGAMW
RKAPPA_ALL = RKAPPA
RLSTT_ALL = RLSTT
RLVTT_ALL = RLVTT
RTT_ALL = RTT
RV_ALL = RV
UDECT_ALL = UDECT
UPRETMAX_ALL = UPRETMAX
UPRETMIN_ALL = UPRETMIN
USHEARM_ALL = USHEARM
USURIC_ALL = USURIC
VKARMN_ALL = VKARMN
KSIZST_ALL = KSIZST
KPTRST_ALL = KPTRST
ICOUNT_ALL = ICOUNT


CALL DATE_AND_TIME (VALUES=ZV0)

PRINT *, "-- RUN"

DO IC = 1, 1

#ifdef GPU
ISTAT = CUDAEVENTCREATE (STARTEVENT)
ISTAT = CUDAEVENTCREATE (STOPEVENT)
ISTAT = CUDAEVENTRECORD (STARTEVENT, 0)

CALL RUN_SIMPLE4_ACTKE <<<ICOUNT, KLON>>> &
#else
CALL RUN_SIMPLE4_ACTKE &
#endif
&                      (KIDIA_ALL, KFDIA_ALL, KLON_ALL, KTDIAT_ALL, KTDIAN_ALL, KLEV_ALL,   &
& PAPHI_ALL, PAPHIF_ALL, PAPRS_ALL, PAPRSF_ALL, PDELP_ALL, PR_ALL, PT_ALL, PU_ALL, PV_ALL, PQ_ALL,  &
& PLSCPE_ALL, PCD_ALL, PCH_ALL, PGZ0_ALL, PTS_ALL, PQS_ALL, PQICE_ALL, PQLI_ALL, PECT_ALL,        &
& PPRODTH_ALL, PNLAB_ALL, PNLABCVP_ALL, PKTROV_ALL, PKUROV_ALL, PXTROV_ALL, PXUROV_ALL,       &
& PNBVNO_ALL, PNEBS_ALL, PQCS_ALL, PNEBS0_ALL, PQCS0_ALL, PCOEFN_ALL, PFECT_ALL, PECT1_ALL,     &
& PTPRDY_ALL, PEDR_ALL, RG_ALL, RPRTH_ALL, ECTMIN_ALL, TSPHY_ALL, ACBRPHIM_ALL, ADISE_ALL,      &
& ADISI_ALL, AKN_ALL, ALD_ALL, ALMAV_ALL, ALMAVE_ALL, ALMAVX_ALL, ALPHAE_ALL, ALPHAT_ALL,       &
& ARSB2_ALL, ARSC1_ALL, ECTMAX_ALL, EDB_ALL, EDC_ALL, EDD_ALL, RALPD_ALL, RALPS_ALL, RALPW_ALL,   &
& RATM_ALL, RBETD_ALL, RBETS_ALL, RBETW_ALL, RCPV_ALL, RCS_ALL, RCW_ALL, RD_ALL, RDT_ALL, RETV_ALL, &
& RGAMD_ALL, RGAMS_ALL, RGAMW_ALL, RKAPPA_ALL, RLSTT_ALL, RLVTT_ALL, RTT_ALL, RV_ALL, UDECT_ALL,  &
& UPRETMAX_ALL, UPRETMIN_ALL, USHEARM_ALL, USURIC_ALL, VKARMN_ALL, KSIZST_ALL, KPTRST_ALL,    &
& PSTACK_ALL, ICOUNT_ALL)

#ifdef GPU
ISTAT = CUDAEVENTRECORD (STOPEVENT, 0)
ISTAT = CUDAEVENTSYNCHRONIZE (STOPEVENT)
ISTAT = CUDAEVENTELAPSEDTIME (TIME, STARTEVENT, STOPEVENT)

PRINT *, " TIME = ", TIME

#else

PRINT *

#endif


ENDDO

#ifdef GPU
ISTAT = CUDADEVICESYNCHRONIZE ()
#endif

CALL DATE_AND_TIME (VALUES=ZV1)

PRINT *, REAL (ZV1 (5) - ZV0 (5), 8) * 3600._8 + REAL (ZV1 (6) - ZV0 (6), 8) * 60._8 + & 
& REAL (ZV1 (7) - ZV0 (7), 8) + REAL (ZV1 (8) - ZV0 (8), 8) / 1000._8


#ifdef UNDEF
WRITE (0, *) __FILE__, ':', __LINE__ 

DO II = 1, 2000
  IFILE = NFILE  (II)
  IF (IFILE == 0) EXIT
  ILINE  = NLINE  (II)
  IIND   = NIND   (II)
  ZVALUE = RVALUE (II)
  WRITE (*, '(A,":",I0," ",I6," ",E20.12)') CHAR (IFILE), ILINE, IIND, ZVALUE
ENDDO
#endif


IF (LLDIFF .AND. ICOUNT0 == ICOUNT1 .AND. KLON0 == KLON1) THEN

PRINT *, "-- DIFF"

DO IBL = 1, ICOUNT

  LLPRINT = .TRUE.
  IF (ASSOCIATED (IDIFFBLOCK)) THEN
    IF (.NOT. ANY (IDIFFBLOCK == IBL)) LLPRINT = .FALSE.
  ENDIF

  IF (LLPRINT) WRITE (*, *) "---", IBL

#define DIFFD(x) CALL DDIFF (#x, x##_ALL, LLPRINT)

  CALL LOAD (ILUN_OUT, IDUM); CALL LOAD (ILUN_OUT, IDUM); CALL LOAD (ILUN_OUT, IDUM); CALL LOAD (ILUN_OUT, IDUM);
  CALL LOAD (ILUN_OUT, IDUM); CALL LOAD (ILUN_OUT, IDUM);
  DIFFD (PAPHI)
  DIFFD (PAPHIF)
  DIFFD (PAPRS)
  DIFFD (PAPRSF)
  DIFFD (PDELP) !
  DIFFD (PR)
  DIFFD (PT)
  DIFFD (PU)
  DIFFD (PV)
  DIFFD (PQ)
  DIFFD (PLSCPE)
  DIFFD (PCD)
  DIFFD (PCH)
  DIFFD (PGZ0)
  DIFFD (PTS)
  DIFFD (PQS)
  DIFFD (PQICE)
  DIFFD (PQLI)
  DIFFD (PECT)
  DIFFD (PPRODTH)
  DIFFD (PNLAB)
  DIFFD (PNLABCVP)
  DIFFD (PKTROV)
  DIFFD (PKUROV)
  DIFFD (PXTROV)
  DIFFD (PXUROV)
  DIFFD (PNBVNO)
  DIFFD (PNEBS)
  DIFFD (PQCS)
  DIFFD (PNEBS0)
  DIFFD (PQCS0)
  DIFFD (PCOEFN)
  DIFFD (PFECT)
  DIFFD (PECT1)
  DIFFD (PTPRDY)
  DIFFD (PEDR)
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
  CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); CALL LOAD (ILUN_OUT, ZDUM); 
ENDDO

ENDIF

CONTAINS

#include "contains.h"

END PROGRAM WRAP_ACTKE
