MODULE YOMLOG

#ifdef GPU
#define ATTR_ARG , DEVICE
USE CUDAFOR
#else
#define ATTR_ARG
#endif


INTEGER, POINTER ATTR_ARG :: IPTR (:) 
INTEGER, POINTER ATTR_ARG :: NFILE (:) 
INTEGER, POINTER ATTR_ARG :: NLINE (:)
INTEGER, POINTER ATTR_ARG :: NIND (:)
REAL, POINTER ATTR_ARG :: RVALUE (:)

END MODULE
