
USE LOAD_MOD, ONLY : ILUNC, ILUN_IN, ILUN_OUT, LOAD, OPEN_LOAD, CLOSE_LOAD
USE SAVE_MOD, ONLY : SAVE, OPEN_SAVE, CLOSE_SAVE
USE PARKIND1
IMPLICIT NONE

INTERFACE RESHAPE_NPROMA
  PROCEDURE RESHAPE_NPROMA_X2
  PROCEDURE RESHAPE_NPROMA_X3
END INTERFACE

INTEGER :: NPROMA
CHARACTER*64 :: CLPROMA

CALL GETARG (1, CLPROMA)

READ (CLPROMA, *) NPROMA


CALL RESHAPE_FILE (ILUN_IN)
CALL RESHAPE_FILE (ILUN_OUT)

CONTAINS

SUBROUTINE RESHAPE_FILE (KLUN)

INTEGER(KIND=JPIM), INTENT (IN) :: KLUN


INTEGER(KIND=JPIM)          :: KIDIA      
INTEGER(KIND=JPIM)          :: KFDIA      
INTEGER(KIND=JPIM)          :: KLON       
INTEGER(KIND=JPIM)          :: KTDIAT     
INTEGER(KIND=JPIM)          :: KTDIAN     
INTEGER(KIND=JPIM)          :: KLEV       
REAL(KIND=JPRB)   , POINTER :: PAPHI      (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPHIF     (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPRS      (:, :)
REAL(KIND=JPRB)   , POINTER :: PAPRSF     (:, :)
REAL(KIND=JPRB)   , POINTER :: PDELP      (:, :)
REAL(KIND=JPRB)   , POINTER :: PR         (:, :)
REAL(KIND=JPRB)   , POINTER :: PT         (:, :)
REAL(KIND=JPRB)   , POINTER :: PU         (:, :)
REAL(KIND=JPRB)   , POINTER :: PV         (:, :)
REAL(KIND=JPRB)   , POINTER :: PQ         (:, :)
REAL(KIND=JPRB)   , POINTER :: PLSCPE     (:, :)
REAL(KIND=JPRB)   , POINTER :: PCD        (:)
REAL(KIND=JPRB)   , POINTER :: PCH        (:)
REAL(KIND=JPRB)   , POINTER :: PGZ0       (:)
REAL(KIND=JPRB)   , POINTER :: PTS        (:)
REAL(KIND=JPRB)   , POINTER :: PQS        (:)
REAL(KIND=JPRB)   , POINTER :: PQICE      (:, :)
REAL(KIND=JPRB)   , POINTER :: PQLI       (:, :)
REAL(KIND=JPRB)   , POINTER :: PECT       (:, :)
REAL(KIND=JPRB)   , POINTER :: PPRODTH    (:, :)
REAL(KIND=JPRB)   , POINTER :: PNLAB      (:, :)
REAL(KIND=JPRB)   , POINTER :: PNLABCVP   (:, :)
REAL(KIND=JPRB)   , POINTER :: PKTROV     (:, :)
REAL(KIND=JPRB)   , POINTER :: PKUROV     (:, :)
REAL(KIND=JPRB)   , POINTER :: PXTROV     (:, :)
REAL(KIND=JPRB)   , POINTER :: PXUROV     (:, :)
REAL(KIND=JPRB)   , POINTER :: PNBVNO     (:, :)
REAL(KIND=JPRB)   , POINTER :: PNEBS      (:, :)
REAL(KIND=JPRB)   , POINTER :: PQCS       (:, :)
REAL(KIND=JPRB)   , POINTER :: PNEBS0     (:, :)
REAL(KIND=JPRB)   , POINTER :: PQCS0      (:, :)
REAL(KIND=JPRB)   , POINTER :: PCOEFN     (:, :)
REAL(KIND=JPRB)   , POINTER :: PFECT      (:, :)
REAL(KIND=JPRB)   , POINTER :: PECT1      (:, :)
REAL(KIND=JPRB)   , POINTER :: PTPRDY     (:, :)
REAL(KIND=JPRB)   , POINTER :: PEDR       (:, :)
REAL(KIND=JPRB)             :: RG         
REAL(KIND=JPRB)             :: RPRTH      
REAL(KIND=JPRB)             :: ECTMIN     
REAL(KIND=JPRB)             :: TSPHY      
REAL(KIND=JPRB)             :: ACBRPHIM   
REAL(KIND=JPRB)             :: ADISE      
REAL(KIND=JPRB)             :: ADISI      
REAL(KIND=JPRB)             :: AKN        
REAL(KIND=JPRB)             :: ALD        
REAL(KIND=JPRB)             :: ALMAV      
REAL(KIND=JPRB)             :: ALMAVE     
REAL(KIND=JPRB)             :: ALMAVX     
REAL(KIND=JPRB)             :: ALPHAE     
REAL(KIND=JPRB)             :: ALPHAT     
REAL(KIND=JPRB)             :: ARSB2      
REAL(KIND=JPRB)             :: ARSC1      
REAL(KIND=JPRB)             :: ECTMAX     
REAL(KIND=JPRB)             :: EDB        
REAL(KIND=JPRB)             :: EDC        
REAL(KIND=JPRB)             :: EDD        
REAL(KIND=JPRB)             :: RALPD      
REAL(KIND=JPRB)             :: RALPS      
REAL(KIND=JPRB)             :: RALPW      
REAL(KIND=JPRB)             :: RATM       
REAL(KIND=JPRB)             :: RBETD      
REAL(KIND=JPRB)             :: RBETS      
REAL(KIND=JPRB)             :: RBETW      
REAL(KIND=JPRB)             :: RCPV       
REAL(KIND=JPRB)             :: RCS        
REAL(KIND=JPRB)             :: RCW        
REAL(KIND=JPRB)             :: RD         
REAL(KIND=JPRB)             :: RDT        
REAL(KIND=JPRB)             :: RETV       
REAL(KIND=JPRB)             :: RGAMD      
REAL(KIND=JPRB)             :: RGAMS      
REAL(KIND=JPRB)             :: RGAMW      
REAL(KIND=JPRB)             :: RKAPPA     
REAL(KIND=JPRB)             :: RLSTT      
REAL(KIND=JPRB)             :: RLVTT      
REAL(KIND=JPRB)             :: RTT        
REAL(KIND=JPRB)             :: RV         
REAL(KIND=JPRB)             :: UDECT      
REAL(KIND=JPRB)             :: UPRETMAX   
REAL(KIND=JPRB)             :: UPRETMIN   
REAL(KIND=JPRB)             :: USHEARM    
REAL(KIND=JPRB)             :: USURIC     
REAL(KIND=JPRB)             :: VKARMN     
INTEGER(KIND=JPIM)          :: NGPBLKS    
INTEGER(KIND=JPIM)          :: KIDIA_2    
INTEGER(KIND=JPIM)          :: KFDIA_2    
INTEGER(KIND=JPIM)          :: KLON_2     
INTEGER(KIND=JPIM)          :: KTDIAT_2   
INTEGER(KIND=JPIM)          :: KTDIAN_2   
INTEGER(KIND=JPIM)          :: KLEV_2     
REAL(KIND=JPRB), POINTER :: PAPHI_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PAPHIF_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PAPRS_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PAPRSF_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PDELP_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PR_2       (:, :, :)
REAL(KIND=JPRB), POINTER :: PT_2       (:, :, :)
REAL(KIND=JPRB), POINTER :: PU_2       (:, :, :)
REAL(KIND=JPRB), POINTER :: PV_2       (:, :, :)
REAL(KIND=JPRB), POINTER :: PQ_2       (:, :, :)
REAL(KIND=JPRB), POINTER :: PLSCPE_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PCD_2      (:, :)
REAL(KIND=JPRB), POINTER :: PCH_2      (:, :)
REAL(KIND=JPRB), POINTER :: PGZ0_2     (:, :)
REAL(KIND=JPRB), POINTER :: PTS_2      (:, :)
REAL(KIND=JPRB), POINTER :: PQS_2      (:, :)
REAL(KIND=JPRB), POINTER :: PQICE_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PQLI_2     (:, :, :)
REAL(KIND=JPRB), POINTER :: PECT_2     (:, :, :)
REAL(KIND=JPRB), POINTER :: PPRODTH_2  (:, :, :)
REAL(KIND=JPRB), POINTER :: PNLAB_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PNLABCVP_2 (:, :, :)
REAL(KIND=JPRB), POINTER :: PKTROV_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PKUROV_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PXTROV_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PXUROV_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PNBVNO_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PNEBS_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PQCS_2     (:, :, :)
REAL(KIND=JPRB), POINTER :: PNEBS0_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PQCS0_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PCOEFN_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PFECT_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PECT1_2    (:, :, :)
REAL(KIND=JPRB), POINTER :: PTPRDY_2   (:, :, :)
REAL(KIND=JPRB), POINTER :: PEDR_2     (:, :, :)
REAL(KIND=JPRB)          :: RG_2       
REAL(KIND=JPRB)          :: RPRTH_2    
REAL(KIND=JPRB)          :: ECTMIN_2   
REAL(KIND=JPRB)          :: TSPHY_2    
REAL(KIND=JPRB)          :: ACBRPHIM_2 
REAL(KIND=JPRB)          :: ADISE_2    
REAL(KIND=JPRB)          :: ADISI_2    
REAL(KIND=JPRB)          :: AKN_2      
REAL(KIND=JPRB)          :: ALD_2      
REAL(KIND=JPRB)          :: ALMAV_2    
REAL(KIND=JPRB)          :: ALMAVE_2   
REAL(KIND=JPRB)          :: ALMAVX_2   
REAL(KIND=JPRB)          :: ALPHAE_2   
REAL(KIND=JPRB)          :: ALPHAT_2   
REAL(KIND=JPRB)          :: ARSB2_2    
REAL(KIND=JPRB)          :: ARSC1_2    
REAL(KIND=JPRB)          :: ECTMAX_2   
REAL(KIND=JPRB)          :: EDB_2      
REAL(KIND=JPRB)          :: EDC_2      
REAL(KIND=JPRB)          :: EDD_2      
REAL(KIND=JPRB)          :: RALPD_2    
REAL(KIND=JPRB)          :: RALPS_2    
REAL(KIND=JPRB)          :: RALPW_2    
REAL(KIND=JPRB)          :: RATM_2     
REAL(KIND=JPRB)          :: RBETD_2    
REAL(KIND=JPRB)          :: RBETS_2    
REAL(KIND=JPRB)          :: RBETW_2    
REAL(KIND=JPRB)          :: RCPV_2     
REAL(KIND=JPRB)          :: RCS_2      
REAL(KIND=JPRB)          :: RCW_2      
REAL(KIND=JPRB)          :: RD_2       
REAL(KIND=JPRB)          :: RDT_2      
REAL(KIND=JPRB)          :: RETV_2     
REAL(KIND=JPRB)          :: RGAMD_2    
REAL(KIND=JPRB)          :: RGAMS_2    
REAL(KIND=JPRB)          :: RGAMW_2    
REAL(KIND=JPRB)          :: RKAPPA_2   
REAL(KIND=JPRB)          :: RLSTT_2    
REAL(KIND=JPRB)          :: RLVTT_2    
REAL(KIND=JPRB)          :: RTT_2      
REAL(KIND=JPRB)          :: RV_2       
REAL(KIND=JPRB)          :: UDECT_2    
REAL(KIND=JPRB)          :: UPRETMAX_2 
REAL(KIND=JPRB)          :: UPRETMIN_2 
REAL(KIND=JPRB)          :: USHEARM_2  
REAL(KIND=JPRB)          :: USURIC_2   
REAL(KIND=JPRB)          :: VKARMN_2   
INTEGER :: IBLOCK
INTEGER :: ISTAT
INTEGER :: JBL, JLO
INTEGER, ALLOCATABLE :: IFDIA (:)


OPEN (ILUNC, FILE="ACTKE.COUNT", FORM="FORMATTED")
READ (ILUNC, *) NGPBLKS
CLOSE (ILUNC)

ALLOCATE (IFDIA (NGPBLKS))

CALL OPEN_LOAD ("ACTKE")
DO IBLOCK = 1, NGPBLKS
  CALL LOAD (KLUN, KIDIA)
  CALL LOAD (KLUN, KFDIA)
  IFDIA (IBLOCK) = KFDIA
  CALL LOAD (KLUN, KLON)
  CALL LOAD (KLUN, KTDIAT)
  CALL LOAD (KLUN, KTDIAN)
  CALL LOAD (KLUN, KLEV)
  CALL LOAD (KLUN, PAPHI)
  CALL LOAD (KLUN, PAPHIF)
  CALL LOAD (KLUN, PAPRS)
  CALL LOAD (KLUN, PAPRSF)
  CALL LOAD (KLUN, PDELP)
  CALL LOAD (KLUN, PR)
  CALL LOAD (KLUN, PT)
  CALL LOAD (KLUN, PU)
  CALL LOAD (KLUN, PV)
  CALL LOAD (KLUN, PQ)
  CALL LOAD (KLUN, PLSCPE)
  CALL LOAD (KLUN, PCD)
  CALL LOAD (KLUN, PCH)
  CALL LOAD (KLUN, PGZ0)
  CALL LOAD (KLUN, PTS)
  CALL LOAD (KLUN, PQS)
  CALL LOAD (KLUN, PQICE)
  CALL LOAD (KLUN, PQLI)
  CALL LOAD (KLUN, PECT)
  CALL LOAD (KLUN, PPRODTH)
  CALL LOAD (KLUN, PNLAB)
  CALL LOAD (KLUN, PNLABCVP)
  CALL LOAD (KLUN, PKTROV)
  CALL LOAD (KLUN, PKUROV)
  CALL LOAD (KLUN, PXTROV)
  CALL LOAD (KLUN, PXUROV)
  CALL LOAD (KLUN, PNBVNO)
  CALL LOAD (KLUN, PNEBS)
  CALL LOAD (KLUN, PQCS)
  CALL LOAD (KLUN, PNEBS0)
  CALL LOAD (KLUN, PQCS0)
  CALL LOAD (KLUN, PCOEFN)
  CALL LOAD (KLUN, PFECT)
  CALL LOAD (KLUN, PECT1)
  CALL LOAD (KLUN, PTPRDY)
  CALL LOAD (KLUN, PEDR)
  CALL LOAD (KLUN, RG)
  CALL LOAD (KLUN, RPRTH)
  CALL LOAD (KLUN, ECTMIN)
  CALL LOAD (KLUN, TSPHY)
  CALL LOAD (KLUN, ACBRPHIM)
  CALL LOAD (KLUN, ADISE)
  CALL LOAD (KLUN, ADISI)
  CALL LOAD (KLUN, AKN)
  CALL LOAD (KLUN, ALD)
  CALL LOAD (KLUN, ALMAV)
  CALL LOAD (KLUN, ALMAVE)
  CALL LOAD (KLUN, ALMAVX)
  CALL LOAD (KLUN, ALPHAE)
  CALL LOAD (KLUN, ALPHAT)
  CALL LOAD (KLUN, ARSB2)
  CALL LOAD (KLUN, ARSC1)
  CALL LOAD (KLUN, ECTMAX)
  CALL LOAD (KLUN, EDB)
  CALL LOAD (KLUN, EDC)
  CALL LOAD (KLUN, EDD)
  CALL LOAD (KLUN, RALPD)
  CALL LOAD (KLUN, RALPS)
  CALL LOAD (KLUN, RALPW)
  CALL LOAD (KLUN, RATM)
  CALL LOAD (KLUN, RBETD)
  CALL LOAD (KLUN, RBETS)
  CALL LOAD (KLUN, RBETW)
  CALL LOAD (KLUN, RCPV)
  CALL LOAD (KLUN, RCS)
  CALL LOAD (KLUN, RCW)
  CALL LOAD (KLUN, RD)
  CALL LOAD (KLUN, RDT)
  CALL LOAD (KLUN, RETV)
  CALL LOAD (KLUN, RGAMD)
  CALL LOAD (KLUN, RGAMS)
  CALL LOAD (KLUN, RGAMW)
  CALL LOAD (KLUN, RKAPPA)
  CALL LOAD (KLUN, RLSTT)
  CALL LOAD (KLUN, RLVTT)
  CALL LOAD (KLUN, RTT)
  CALL LOAD (KLUN, RV)
  CALL LOAD (KLUN, UDECT)
  CALL LOAD (KLUN, UPRETMAX)
  CALL LOAD (KLUN, UPRETMIN)
  CALL LOAD (KLUN, USHEARM)
  CALL LOAD (KLUN, USURIC)
  CALL LOAD (KLUN, VKARMN)
  IF (IBLOCK == 1) THEN
    ALLOCATE (PAPHI_2 (KLON, LBOUND (PAPHI, 2):UBOUND (PAPHI, 2), NGPBLKS))
    ALLOCATE (PAPHIF_2 (KLON, LBOUND (PAPHIF, 2):UBOUND (PAPHIF, 2), NGPBLKS))
    ALLOCATE (PAPRS_2 (KLON, LBOUND (PAPRS, 2):UBOUND (PAPRS, 2), NGPBLKS))
    ALLOCATE (PAPRSF_2 (KLON, LBOUND (PAPRSF, 2):UBOUND (PAPRSF, 2), NGPBLKS))
    ALLOCATE (PDELP_2 (KLON, LBOUND (PDELP, 2):UBOUND (PDELP, 2), NGPBLKS))
    ALLOCATE (PR_2 (KLON, LBOUND (PR, 2):UBOUND (PR, 2), NGPBLKS))
    ALLOCATE (PT_2 (KLON, LBOUND (PT, 2):UBOUND (PT, 2), NGPBLKS))
    ALLOCATE (PU_2 (KLON, LBOUND (PU, 2):UBOUND (PU, 2), NGPBLKS))
    ALLOCATE (PV_2 (KLON, LBOUND (PV, 2):UBOUND (PV, 2), NGPBLKS))
    ALLOCATE (PQ_2 (KLON, LBOUND (PQ, 2):UBOUND (PQ, 2), NGPBLKS))
    ALLOCATE (PLSCPE_2 (KLON, LBOUND (PLSCPE, 2):UBOUND (PLSCPE, 2), NGPBLKS))
    ALLOCATE (PCD_2 (KLON, NGPBLKS))
    ALLOCATE (PCH_2 (KLON, NGPBLKS))
    ALLOCATE (PGZ0_2 (KLON, NGPBLKS))
    ALLOCATE (PTS_2 (KLON, NGPBLKS))
    ALLOCATE (PQS_2 (KLON, NGPBLKS))
    ALLOCATE (PQICE_2 (KLON, LBOUND (PQICE, 2):UBOUND (PQICE, 2), NGPBLKS))
    ALLOCATE (PQLI_2 (KLON, LBOUND (PQLI, 2):UBOUND (PQLI, 2), NGPBLKS))
    ALLOCATE (PECT_2 (KLON, LBOUND (PECT, 2):UBOUND (PECT, 2), NGPBLKS))
    ALLOCATE (PPRODTH_2 (KLON, LBOUND (PPRODTH, 2):UBOUND (PPRODTH, 2), NGPBLKS))
    ALLOCATE (PNLAB_2 (KLON, LBOUND (PNLAB, 2):UBOUND (PNLAB, 2), NGPBLKS))
    ALLOCATE (PNLABCVP_2 (KLON, LBOUND (PNLABCVP, 2):UBOUND (PNLABCVP, 2), NGPBLKS))
    ALLOCATE (PKTROV_2 (KLON, LBOUND (PKTROV, 2):UBOUND (PKTROV, 2), NGPBLKS))
    ALLOCATE (PKUROV_2 (KLON, LBOUND (PKUROV, 2):UBOUND (PKUROV, 2), NGPBLKS))
    ALLOCATE (PXTROV_2 (KLON, LBOUND (PXTROV, 2):UBOUND (PXTROV, 2), NGPBLKS))
    ALLOCATE (PXUROV_2 (KLON, LBOUND (PXUROV, 2):UBOUND (PXUROV, 2), NGPBLKS))
    ALLOCATE (PNBVNO_2 (KLON, LBOUND (PNBVNO, 2):UBOUND (PNBVNO, 2), NGPBLKS))
    ALLOCATE (PNEBS_2 (KLON, LBOUND (PNEBS, 2):UBOUND (PNEBS, 2), NGPBLKS))
    ALLOCATE (PQCS_2 (KLON, LBOUND (PQCS, 2):UBOUND (PQCS, 2), NGPBLKS))
    ALLOCATE (PNEBS0_2 (KLON, LBOUND (PNEBS0, 2):UBOUND (PNEBS0, 2), NGPBLKS))
    ALLOCATE (PQCS0_2 (KLON, LBOUND (PQCS0, 2):UBOUND (PQCS0, 2), NGPBLKS))
    ALLOCATE (PCOEFN_2 (KLON, LBOUND (PCOEFN, 2):UBOUND (PCOEFN, 2), NGPBLKS))
    ALLOCATE (PFECT_2 (KLON, LBOUND (PFECT, 2):UBOUND (PFECT, 2), NGPBLKS))
    ALLOCATE (PECT1_2 (KLON, LBOUND (PECT1, 2):UBOUND (PECT1, 2), NGPBLKS))
    ALLOCATE (PTPRDY_2 (KLON, LBOUND (PTPRDY, 2):UBOUND (PTPRDY, 2), NGPBLKS))
    ALLOCATE (PEDR_2 (KLON, LBOUND (PEDR, 2):UBOUND (PEDR, 2), NGPBLKS))
  ENDIF
  PAPHI_2 (:, :, IBLOCK) = PAPHI
  PAPHIF_2 (:, :, IBLOCK) = PAPHIF
  PAPRS_2 (:, :, IBLOCK) = PAPRS
  PAPRSF_2 (:, :, IBLOCK) = PAPRSF
  PDELP_2 (:, :, IBLOCK) = PDELP
  PR_2 (:, :, IBLOCK) = PR
  PT_2 (:, :, IBLOCK) = PT
  PU_2 (:, :, IBLOCK) = PU
  PV_2 (:, :, IBLOCK) = PV
  PQ_2 (:, :, IBLOCK) = PQ
  PLSCPE_2 (:, :, IBLOCK) = PLSCPE
  PCD_2 (:, IBLOCK) = PCD
  PCH_2 (:, IBLOCK) = PCH
  PGZ0_2 (:, IBLOCK) = PGZ0
  PTS_2 (:, IBLOCK) = PTS
  PQS_2 (:, IBLOCK) = PQS
  PQICE_2 (:, :, IBLOCK) = PQICE
  PQLI_2 (:, :, IBLOCK) = PQLI
  PECT_2 (:, :, IBLOCK) = PECT
  PPRODTH_2 (:, :, IBLOCK) = PPRODTH
  PNLAB_2 (:, :, IBLOCK) = PNLAB
  PNLABCVP_2 (:, :, IBLOCK) = PNLABCVP
  PKTROV_2 (:, :, IBLOCK) = PKTROV
  PKUROV_2 (:, :, IBLOCK) = PKUROV
  PXTROV_2 (:, :, IBLOCK) = PXTROV
  PXUROV_2 (:, :, IBLOCK) = PXUROV
  PNBVNO_2 (:, :, IBLOCK) = PNBVNO
  PNEBS_2 (:, :, IBLOCK) = PNEBS
  PQCS_2 (:, :, IBLOCK) = PQCS
  PNEBS0_2 (:, :, IBLOCK) = PNEBS0
  PQCS0_2 (:, :, IBLOCK) = PQCS0
  PCOEFN_2 (:, :, IBLOCK) = PCOEFN
  PFECT_2 (:, :, IBLOCK) = PFECT
  PECT1_2 (:, :, IBLOCK) = PECT1
  PTPRDY_2 (:, :, IBLOCK) = PTPRDY
  PEDR_2 (:, :, IBLOCK) = PEDR
  DEALLOCATE (PAPHI)
  DEALLOCATE (PAPHIF)
  DEALLOCATE (PAPRS)
  DEALLOCATE (PAPRSF)
  DEALLOCATE (PDELP)
  DEALLOCATE (PR)
  DEALLOCATE (PT)
  DEALLOCATE (PU)
  DEALLOCATE (PV)
  DEALLOCATE (PQ)
  DEALLOCATE (PLSCPE)
  DEALLOCATE (PCD)
  DEALLOCATE (PCH)
  DEALLOCATE (PGZ0)
  DEALLOCATE (PTS)
  DEALLOCATE (PQS)
  DEALLOCATE (PQICE)
  DEALLOCATE (PQLI)
  DEALLOCATE (PECT)
  DEALLOCATE (PPRODTH)
  DEALLOCATE (PNLAB)
  DEALLOCATE (PNLABCVP)
  DEALLOCATE (PKTROV)
  DEALLOCATE (PKUROV)
  DEALLOCATE (PXTROV)
  DEALLOCATE (PXUROV)
  DEALLOCATE (PNBVNO)
  DEALLOCATE (PNEBS)
  DEALLOCATE (PQCS)
  DEALLOCATE (PNEBS0)
  DEALLOCATE (PQCS0)
  DEALLOCATE (PCOEFN)
  DEALLOCATE (PFECT)
  DEALLOCATE (PECT1)
  DEALLOCATE (PTPRDY)
  DEALLOCATE (PEDR)
ENDDO
CALL CLOSE_LOAD

CALL RESHAPE_NPROMA (PAPHI_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PAPHIF_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PAPRS_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PAPRSF_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PDELP_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PR_2,        NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PT_2,        NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PU_2,        NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PV_2,        NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PQ_2,        NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PLSCPE_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PCD_2,       NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PCH_2,       NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PGZ0_2,      NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PTS_2,       NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PQS_2,       NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PQICE_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PQLI_2,      NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PECT_2,      NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PPRODTH_2,   NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PNLAB_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PNLABCVP_2,  NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PKTROV_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PKUROV_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PXTROV_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PXUROV_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PNBVNO_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PNEBS_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PQCS_2,      NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PNEBS0_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PQCS0_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PCOEFN_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PFECT_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PECT1_2,     NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PTPRDY_2,    NPROMA,  IFDIA )
CALL RESHAPE_NPROMA (PEDR_2,      NPROMA,  IFDIA )

WRITE (0, *) " NPROMA = ", KLON, " NGPBLKS = ", NGPBLKS

NGPBLKS = 1 + (KLON * NGPBLKS - 1) / NPROMA

WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS

OPEN (ILUNC, FILE="ACTKE."//TRIM (CLPROMA)//".COUNT", FORM="FORMATTED")
WRITE (ILUNC, *) NGPBLKS
CLOSE (ILUNC)


KIDIA = 1
KFDIA = NPROMA
KLON  = NPROMA

CALL OPEN_SAVE ("ACTKE."//TRIM (CLPROMA))
DO IBLOCK = 1, NGPBLKS
  PAPHI    => PAPHI_2 (:, :, IBLOCK)       
  PAPHIF   => PAPHIF_2 (:, :, IBLOCK)      
  PAPRS    => PAPRS_2 (:, :, IBLOCK)       
  PAPRSF   => PAPRSF_2 (:, :, IBLOCK)      
  PDELP    => PDELP_2 (:, :, IBLOCK)       
  PR       => PR_2 (:, :, IBLOCK)          
  PT       => PT_2 (:, :, IBLOCK)          
  PU       => PU_2 (:, :, IBLOCK)          
  PV       => PV_2 (:, :, IBLOCK)          
  PQ       => PQ_2 (:, :, IBLOCK)          
  PLSCPE   => PLSCPE_2 (:, :, IBLOCK)      
  PCD      => PCD_2 (:, IBLOCK)            
  PCH      => PCH_2 (:, IBLOCK)            
  PGZ0     => PGZ0_2 (:, IBLOCK)           
  PTS      => PTS_2 (:, IBLOCK)            
  PQS      => PQS_2 (:, IBLOCK)            
  PQICE    => PQICE_2 (:, :, IBLOCK)       
  PQLI     => PQLI_2 (:, :, IBLOCK)        
  PECT     => PECT_2 (:, :, IBLOCK)        
  PPRODTH  => PPRODTH_2 (:, :, IBLOCK)     
  PNLAB    => PNLAB_2 (:, :, IBLOCK)       
  PNLABCVP => PNLABCVP_2 (:, :, IBLOCK)    
  PKTROV   => PKTROV_2 (:, :, IBLOCK)      
  PKUROV   => PKUROV_2 (:, :, IBLOCK)      
  PXTROV   => PXTROV_2 (:, :, IBLOCK)      
  PXUROV   => PXUROV_2 (:, :, IBLOCK)      
  PNBVNO   => PNBVNO_2 (:, :, IBLOCK)      
  PNEBS    => PNEBS_2 (:, :, IBLOCK)       
  PQCS     => PQCS_2 (:, :, IBLOCK)        
  PNEBS0   => PNEBS0_2 (:, :, IBLOCK)      
  PQCS0    => PQCS0_2 (:, :, IBLOCK)       
  PCOEFN   => PCOEFN_2 (:, :, IBLOCK)      
  PFECT    => PFECT_2 (:, :, IBLOCK)       
  PECT1    => PECT1_2 (:, :, IBLOCK)       
  PTPRDY   => PTPRDY_2 (:, :, IBLOCK)      
  PEDR     => PEDR_2 (:, :, IBLOCK)        
  CALL SAVE (KLUN, KIDIA)
  CALL SAVE (KLUN, KFDIA)
  CALL SAVE (KLUN, KLON)
  CALL SAVE (KLUN, KTDIAT)
  CALL SAVE (KLUN, KTDIAN)
  CALL SAVE (KLUN, KLEV)
  CALL SAVE (KLUN, PAPHI)
  CALL SAVE (KLUN, PAPHIF)
  CALL SAVE (KLUN, PAPRS)
  CALL SAVE (KLUN, PAPRSF)
  CALL SAVE (KLUN, PDELP)
  CALL SAVE (KLUN, PR)
  CALL SAVE (KLUN, PT)
  CALL SAVE (KLUN, PU)
  CALL SAVE (KLUN, PV)
  CALL SAVE (KLUN, PQ)
  CALL SAVE (KLUN, PLSCPE)
  CALL SAVE (KLUN, PCD)
  CALL SAVE (KLUN, PCH)
  CALL SAVE (KLUN, PGZ0)
  CALL SAVE (KLUN, PTS)
  CALL SAVE (KLUN, PQS)
  CALL SAVE (KLUN, PQICE)
  CALL SAVE (KLUN, PQLI)
  CALL SAVE (KLUN, PECT)
  CALL SAVE (KLUN, PPRODTH)
  CALL SAVE (KLUN, PNLAB)
  CALL SAVE (KLUN, PNLABCVP)
  CALL SAVE (KLUN, PKTROV)
  CALL SAVE (KLUN, PKUROV)
  CALL SAVE (KLUN, PXTROV)
  CALL SAVE (KLUN, PXUROV)
  CALL SAVE (KLUN, PNBVNO)
  CALL SAVE (KLUN, PNEBS)
  CALL SAVE (KLUN, PQCS)
  CALL SAVE (KLUN, PNEBS0)
  CALL SAVE (KLUN, PQCS0)
  CALL SAVE (KLUN, PCOEFN)
  CALL SAVE (KLUN, PFECT)
  CALL SAVE (KLUN, PECT1)
  CALL SAVE (KLUN, PTPRDY)
  CALL SAVE (KLUN, PEDR)
  CALL SAVE (KLUN, RG)
  CALL SAVE (KLUN, RPRTH)
  CALL SAVE (KLUN, ECTMIN)
  CALL SAVE (KLUN, TSPHY)
  CALL SAVE (KLUN, ACBRPHIM)
  CALL SAVE (KLUN, ADISE)
  CALL SAVE (KLUN, ADISI)
  CALL SAVE (KLUN, AKN)
  CALL SAVE (KLUN, ALD)
  CALL SAVE (KLUN, ALMAV)
  CALL SAVE (KLUN, ALMAVE)
  CALL SAVE (KLUN, ALMAVX)
  CALL SAVE (KLUN, ALPHAE)
  CALL SAVE (KLUN, ALPHAT)
  CALL SAVE (KLUN, ARSB2)
  CALL SAVE (KLUN, ARSC1)
  CALL SAVE (KLUN, ECTMAX)
  CALL SAVE (KLUN, EDB)
  CALL SAVE (KLUN, EDC)
  CALL SAVE (KLUN, EDD)
  CALL SAVE (KLUN, RALPD)
  CALL SAVE (KLUN, RALPS)
  CALL SAVE (KLUN, RALPW)
  CALL SAVE (KLUN, RATM)
  CALL SAVE (KLUN, RBETD)
  CALL SAVE (KLUN, RBETS)
  CALL SAVE (KLUN, RBETW)
  CALL SAVE (KLUN, RCPV)
  CALL SAVE (KLUN, RCS)
  CALL SAVE (KLUN, RCW)
  CALL SAVE (KLUN, RD)
  CALL SAVE (KLUN, RDT)
  CALL SAVE (KLUN, RETV)
  CALL SAVE (KLUN, RGAMD)
  CALL SAVE (KLUN, RGAMS)
  CALL SAVE (KLUN, RGAMW)
  CALL SAVE (KLUN, RKAPPA)
  CALL SAVE (KLUN, RLSTT)
  CALL SAVE (KLUN, RLVTT)
  CALL SAVE (KLUN, RTT)
  CALL SAVE (KLUN, RV)
  CALL SAVE (KLUN, UDECT)
  CALL SAVE (KLUN, UPRETMAX)
  CALL SAVE (KLUN, UPRETMIN)
  CALL SAVE (KLUN, USHEARM)
  CALL SAVE (KLUN, USURIC)
  CALL SAVE (KLUN, VKARMN)
ENDDO
CALL CLOSE_SAVE


END SUBROUTINE



SUBROUTINE RESHAPE_NPROMA_X2 (PA, KPROMB, KFDIA)

REAL(KIND=JPRB),    POINTER     :: PA (:, :)
INTEGER(KIND=JPIM), INTENT (IN) :: KPROMB, KFDIA (:)

REAL(KIND=JPRB), POINTER :: ZB (:,:)
INTEGER(KIND=JPIM) :: IGPBLKA, IGPBLKB, IPROMA, IFDIA
INTEGER(KIND=JPIM) :: JBLA, JLOA, II, JBLB, JLOB

IPROMA  = SIZE (PA, 1)
IGPBLKA = SIZE (PA, 2)
IGPBLKB = 1 + (IPROMA * IGPBLKA - 1) / KPROMB

ALLOCATE (ZB (KPROMB, IGPBLKB))
ZB = -999.999_JPRB

DO JBLA = 1, IGPBLKA
  DO JLOA = 1, IPROMA
    II = JLOA + (JBLA - 1) * IPROMA
    JBLB = 1 + (II - 1) / KPROMB
    JLOB = 1 + MODULO (II - 1, KPROMB)
    IFDIA = KFDIA (JBLA)
    IF (JLOA <= IFDIA) THEN
      ZB (JLOB, JBLB) = PA (JLOA, JBLA)
    ELSE
      ZB (JLOB, JBLB) = PA (IFDIA, JBLA)
    ENDIF
!   PRINT *, "(", JLOB, ",", JBLB, ") <- (", JLOA, ",", JBLA, ")"
  ENDDO
ENDDO

DO II = IGPBLKA * IPROMA + 1, IGPBLKB * KPROMB
  JBLB = 1 + (II - 1) / KPROMB
  JLOB = 1 + MODULO (II - 1, KPROMB)
  ZB (JLOB, JBLB) = ZB (JLOB-1, JBLB)
! PRINT *, "(", JLOB, ",", JBLB, ") <- (", JLOB-1, ",", JBLB, ")"
ENDDO

DEALLOCATE (PA)
PA => ZB

END SUBROUTINE

SUBROUTINE RESHAPE_NPROMA_X3 (PA, KPROMB, KFDIA)
REAL(KIND=JPRB),    POINTER     :: PA (:, :, :)
INTEGER(KIND=JPIM), INTENT (IN) :: KPROMB, KFDIA (:)

REAL(KIND=JPRB), POINTER :: ZB (:,:,:)
INTEGER(KIND=JPIM) :: IGPBLKA, IGPBLKB, IPROMA, IFDIA
INTEGER(KIND=JPIM) :: JBLA, JLOA, II, JBLB, JLOB

IPROMA  = SIZE (PA, 1)
IGPBLKA = SIZE (PA, 3)
IGPBLKB = 1 + (IPROMA * IGPBLKA - 1) / KPROMB

ALLOCATE (ZB (KPROMB, SIZE (PA, 2), IGPBLKB))

DO JBLA = 1, IGPBLKA
  DO JLOA = 1, IPROMA
    II = JLOA + (JBLA - 1) * IPROMA
    JBLB = 1 + (II - 1) / KPROMB
    JLOB = 1 + MODULO (II - 1, KPROMB)
    IFDIA = KFDIA (JBLA)
    IF (JLOA <= IFDIA) THEN
      ZB (JLOB, :, JBLB) = PA (JLOA, :, JBLA)
    ELSE
      ZB (JLOB, :, JBLB) = PA (IFDIA, :, JBLA)
    ENDIF
  ENDDO
ENDDO

DO II = IGPBLKA * IPROMA + 1, IGPBLKB * KPROMB
  JBLB = 1 + (II - 1) / KPROMB
  JLOB = 1 + MODULO (II - 1, KPROMB)
  ZB (JLOB, :, JBLB) = ZB (JLOB-1, :, JBLB)
ENDDO

DEALLOCATE (PA)
PA => ZB


END SUBROUTINE

END
