MODULE SAVE_MOD

USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

INTERFACE SAVE
MODULE PROCEDURE SAVEX0
MODULE PROCEDURE SAVEX1
MODULE PROCEDURE SAVEX2
MODULE PROCEDURE SAVEI0
MODULE PROCEDURE SAVEL0
MODULE PROCEDURE SAVEC0
END INTERFACE SAVE

INTEGER, PARAMETER :: ILUN_IN = 77, ILUN_OUT = 88, ILUNC = 99
INTEGER, PARAMETER :: MYPROC = 1

CONTAINS

SUBROUTINE OPEN_SAVE (CDFILE)
CHARACTER (LEN=*), INTENT (IN) :: CDFILE
LOGICAL :: LLEXIST


INQUIRE (FILE=TRIM (CDFILE)//'.OUT', EXIST=LLEXIST)

IF (LLEXIST) THEN
  OPEN (ILUN_IN , FILE=TRIM (CDFILE)//'.IN',   FORM='UNFORMATTED', STATUS="OLD", POSITION="APPEND", ACTION="WRITE")
  OPEN (ILUN_OUT, FILE=TRIM (CDFILE)//'.OUT',  FORM='UNFORMATTED', STATUS="OLD", POSITION="APPEND", ACTION="WRITE")
ELSE
  OPEN (ILUN_IN,  FILE=TRIM (CDFILE)//'.IN' , FORM='UNFORMATTED', STATUS="NEW", ACTION="WRITE")
  OPEN (ILUN_OUT, FILE=TRIM (CDFILE)//'.OUT', FORM='UNFORMATTED', STATUS="NEW", ACTION="WRITE")
END IF

END SUBROUTINE OPEN_SAVE

SUBROUTINE CLOSE_SAVE
CLOSE (ILUN_IN)
CLOSE (ILUN_OUT)
END SUBROUTINE CLOSE_SAVE

SUBROUTINE SAVEX0 (ILUN, X0) 
INTEGER          :: ILUN
REAL (KIND=JPRB) :: X0
WRITE (ILUN) X0
END SUBROUTINE SAVEX0

SUBROUTINE SAVEX1 (ILUN, X1) 
INTEGER          :: ILUN
REAL (KIND=JPRB) :: X1 (:) 
WRITE (ILUN) LBOUND (X1)
WRITE (ILUN) UBOUND (X1)
WRITE (ILUN) X1
END SUBROUTINE SAVEX1

SUBROUTINE SAVEX2 (ILUN, X2) 
INTEGER          :: ILUN
REAL (KIND=JPRB) :: X2 (:,:)
WRITE (ILUN) LBOUND (X2)
WRITE (ILUN) UBOUND (X2)
WRITE (ILUN) X2
END SUBROUTINE SAVEX2

SUBROUTINE SAVEI0 (ILUN, I0)
INTEGER             :: ILUN
INTEGER (KIND=JPIM) :: I0
WRITE (ILUN) I0
END SUBROUTINE SAVEI0

SUBROUTINE SAVEL0 (ILUN, L0)
INTEGER :: ILUN
LOGICAL :: L0
WRITE (ILUN) L0
END SUBROUTINE SAVEL0

SUBROUTINE SAVEC0 (ILUN, C0)
INTEGER           :: ILUN
CHARACTER (LEN=*) :: C0
WRITE (ILUN) C0
END SUBROUTINE SAVEC0

END MODULE SAVE_MOD

